<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>lvarezcascales</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ÁlvarezCascales_files/libs/clipboard/clipboard.min.js"></script>
<script src="ÁlvarezCascales_files/libs/quarto-html/quarto.js"></script>
<script src="ÁlvarezCascales_files/libs/quarto-html/popper.min.js"></script>
<script src="ÁlvarezCascales_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ÁlvarezCascales_files/libs/quarto-html/anchor.min.js"></script>
<link href="ÁlvarezCascales_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ÁlvarezCascales_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ÁlvarezCascales_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ÁlvarezCascales_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ÁlvarezCascales_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="características-corporales-de-hombres-adultos-y-su-relación-con-la-grasa-acumulada." class="level1">
<h1>CARACTERÍSTICAS CORPORALES DE HOMBRES ADULTOS Y SU RELACIÓN CON LA GRASA ACUMULADA.</h1>
<section id="introducción" class="level3">
<h3 class="anchored" data-anchor-id="introducción">INTRODUCCIÓN</h3>
<p>El dataset en el que se basa este informe, recoge medidas de la circunferencia de varias partes del cuerpo de 252 hombres, junto con su altura, su peso, su densidad (en el agua) y su porcentaje de grasa corporal.</p>
<p>Este conjunto de datos se recopiló con la pretensión de poder sacar conclusiones acerca de como afecta el aumento de grasa acumulada, en la estructura corporal de los hombres.</p>
<p>Es de resaltar que una variedad de libros sobre salud sugieren que los lectores evalúen su salud, al menos en parte, estimando su porcentaje de grasa corporal. En Bailey (1994), por ejemplo, el lector puede estimar la grasa corporal a partir de tablas utilizando su edad y varias mediciones de pliegues cutáneos obtenidas mediante el uso de un calibrador. Otros textos proporcionan ecuaciones predictivas para la grasa corporal utilizando medidas de circunferencia corporal (por ejemplo, circunferencia abdominal) y/o mediciones de pliegues cutáneos. Véase, por ejemplo, Behnke y Wilmore (1974), pp.&nbsp;66-67; Wilmore (1976), p.&nbsp;247; o Katch y McArdle (1977), pp.&nbsp;120-132).</p>
<p>Para finalizar esta introducción, resulta relevante mencionar que porcentajes de grasa corporal altos, llevan a la persona a padecer sobrepeso y obesidad, condiciones que acarrean riesgos severos para la salud como presión arterial alta (hipertensión), colesterol LDL alto, colesterol HDL bajo o niveles altos de triglicéridos (dislipidemia), diabetes tipo 2, enfermedad coronaria, derrame cerebral o apnea del sueño y problemas respiratorios entre otros, que dan lugar a una baja calidad de vida y reducción del bienestar.</p>
<p>Se considera que un hombre de <strong>entre 20 y 39 años</strong> tendrá sobrepeso si su porcentaje de grasa corporal está entre el 20 y 25% y será obeso si el porcentaje supera el 25%. Pero si su edad está <strong>entre 40 y 59 años,</strong> el sobrepeso se da con un 22-28% y la obesidad con cifras superiores al 28%. Y para los mas mayores, por encima de los <strong>65 años,</strong> el sobrepeso está entre el 25 y 30%, mientras que obesidad en porcentajes superiores al 30% de grasa corporal.</p>
<p>Por otro lado, la cuantía mínima de grasa corporal para la vida humana es de entorno al 3%. Es el porcentaje mínimo necesario para lograr realizar funciones vitales del organismo.</p>
<p>Además, es destacable mencionar que normalmente las disciplinas deportivas tienen unos estándares de porcentaje de grasa corporal asociados. Por ejemplo, en el caso del fútbol, <strong>la media se establece en el 10%</strong>. Un delantero como Ronaldo se sitúa por debajo de este porcentaje, lo que favorece su agilidad. No obstante, un defensa puede tener una cantidad de grasa corporal algo superior para soportar mejor los choques. Destacan sobretodo las pruebas de <strong>resistencia extrema</strong>, como maratones, por ser donde se encuentran los deportistas con menor porcentaje de grasa corporal, con números que se acercan al 4%. También en el culturismo o en el ciclismo. Alberto Contador, por ejemplo, en su momento de estado óptimo rondaba esta cifra.</p>
</section>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset">DATASET</h3>
<p>El conjunto de datos se llama `bodyfat.csv’ y presenta 15 variables que recogen datos de 252 hombres.</p>
<p>Las variables recogidas son:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">'bodyfat.csv'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Density" "BodyFat" "Age"     "Weight"  "Height"  "Neck"    "Chest"  
 [8] "Abdomen" "Hip"     "Thigh"   "Knee"    "Ankle"   "Biceps"  "Forearm"
[15] "Wrist"  </code></pre>
</div>
</div>
<p>i).Density: Variable cuantitativa que se refiere a la <u>densidad del cuerpo</u> determinada mediante un pesaje <u>bajo el agua</u>. Se mide en <u>g/cm^3</u></p>
<p>ii)BodyFat: <u>Porcentaje de grasa corporal</u>.</p>
<p>iii).Age: <u>Edad</u> del individuo, en <u>años.</u></p>
<p>iv).Weight: <u>Peso del individuo</u>, medido en libras. (lb)</p>
<p>v).Height: <u>Altura</u> en pulgadas (in)</p>
<p>vi).Neck: <u>Circunferencia del Cuello.</u> (cm)</p>
<p>vii). Chest: <u>Circunferencia del Pecho</u>. (cm)</p>
<p>viii).Abdomen: <u>Circunferencia del Abdomen</u>. (cm)</p>
<p>ix).Hip: <u>Circunferencia de la cadera</u>. (cm)</p>
<p>x).Thigh: <u>Circunferencia del Muslo</u>. (cm)</p>
<p>xi).Knee: <u>Circunferencia de la Rodilla.</u> (cm)</p>
<p>xii). Anckle: <u>Circunferencia del Tobillo</u>. (cm)</p>
<p>xiii).Biceps: <u>Circunferencia del Biceps.</u> (cm)</p>
<p>xiv).Forearm: <u>Circunferencia del Antebrazo</u>. (cm)</p>
<p>xv).Wrist: <u>Circunferencia de la Muñeca.</u> (cm)</p>
<p>El conjunto de datos proviene de la página web kaggle (<a href="https://www.kaggle.com/datasets/fedesoriano/body-fat-prediction-dataset" class="uri">https://www.kaggle.com/datasets/fedesoriano/body-fat-prediction-dataset</a>)</p>
<p>El dataset fue inicialmente distribuido por el Doctor A. Garth Fisher, quien dió permiso para redistribuirlo con fines no comerciales. Concretamente la persona que lo subió a la web lo obtuvo del Departamento de Matemáticas y Ciencias de la Computación de la Escuala de minas y Tecnología de Sur Dakota.</p>
<p><em>Roger W. Johnson</em></p>
<p><em>Department of Mathematics &amp; Computer Science</em></p>
<p><em>South Dakota School of Mines &amp; Technology</em></p>
<p><em>501 East St.&nbsp;Joseph Street</em></p>
<p><em>Rapid City, SD 57701</em></p>
</section>
<section id="estudio-inical-de-los-datos" class="level3">
<h3 class="anchored" data-anchor-id="estudio-inical-de-los-datos">ESTUDIO INICAL DE LOS DATOS</h3>
<ul>
<li><strong>Primeramente conviene visualizar un resumen de las variables</strong> (dado que son 15 variables y puede que no se visualicen bien, lo hacemos en 3 grupos)</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Density         BodyFat           Age            Weight     
 Min.   :0.995   Min.   : 0.00   Min.   :22.00   Min.   :118.5  
 1st Qu.:1.041   1st Qu.:12.47   1st Qu.:35.75   1st Qu.:159.0  
 Median :1.055   Median :19.20   Median :43.00   Median :176.5  
 Mean   :1.056   Mean   :19.15   Mean   :44.88   Mean   :178.9  
 3rd Qu.:1.070   3rd Qu.:25.30   3rd Qu.:54.00   3rd Qu.:197.0  
 Max.   :1.109   Max.   :47.50   Max.   :81.00   Max.   :363.1  
     Height     
 Min.   :64.00  
 1st Qu.:68.25  
 Median :70.00  
 Mean   :70.31  
 3rd Qu.:72.25  
 Max.   :77.75  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Neck           Chest           Abdomen            Hip       
 Min.   :31.10   Min.   : 79.30   Min.   : 69.40   Min.   : 85.0  
 1st Qu.:36.40   1st Qu.: 94.35   1st Qu.: 84.58   1st Qu.: 95.5  
 Median :38.00   Median : 99.65   Median : 90.95   Median : 99.3  
 Mean   :37.99   Mean   :100.82   Mean   : 92.56   Mean   : 99.9  
 3rd Qu.:39.42   3rd Qu.:105.38   3rd Qu.: 99.33   3rd Qu.:103.5  
 Max.   :51.20   Max.   :136.20   Max.   :148.10   Max.   :147.7  
     Thigh      
 Min.   :47.20  
 1st Qu.:56.00  
 Median :59.00  
 Mean   :59.41  
 3rd Qu.:62.35  
 Max.   :87.30  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Knee           Ankle          Biceps         Forearm          Wrist      
 Min.   :33.00   Min.   :19.1   Min.   :24.80   Min.   :21.00   Min.   :15.80  
 1st Qu.:36.98   1st Qu.:22.0   1st Qu.:30.20   1st Qu.:27.30   1st Qu.:17.60  
 Median :38.50   Median :22.8   Median :32.05   Median :28.70   Median :18.30  
 Mean   :38.59   Mean   :23.1   Mean   :32.27   Mean   :28.66   Mean   :18.23  
 3rd Qu.:39.92   3rd Qu.:24.0   3rd Qu.:34.33   3rd Qu.:30.00   3rd Qu.:18.80  
 Max.   :49.10   Max.   :33.9   Max.   :45.00   Max.   :34.90   Max.   :21.40  </code></pre>
</div>
</div>
<p>Resulta peculiar ver que en el resumen de la variable BodyFat, (porcentaje de grasa corporal), haya individuos con un porcentaje de grasa igual a 0, cuando en la busqueda por internet vimos que la cuantía mínima de grasa corporal para la vida humana es del 3%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(d<span class="sc">$</span>BodyFat <span class="sc">&lt;</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Density BodyFat Age Weight Height Neck Chest Abdomen  Hip Thigh Knee Ankle
172  1.0983     0.7  35 125.75   65.5 34.0  90.8    75.0 89.2  50.0 34.8  22.0
182  1.1089     0.0  40 118.50   68.0 33.8  79.3    69.4 85.0  47.2 33.5  20.2
    Biceps Forearm Wrist
172   24.8    25.9  16.9
182   27.7    24.6  16.5</code></pre>
</div>
</div>
<p>Concretamente hay <u>dos individuos para los que el porcentaje de grasa corporal, cae por debajo del mínimo necesario para la vida.</u> Estas observaciones atípicas son las de los individuos 172 y 182, con porcentajes de grasa corporal del 0.7 y del 0 % respectivamente. Leyendo en la propia página Kaggle, de la que proviene el conjunto de datos, resulta que muy probablemente haya una medición errónea en la densidad corporal de estos dos individuos. Por ahora solo los tendremos en cuenta, pero no los eliminamos ya que nos pueden servir en pasos posteriores.</p>
<p>Entre otros aspectos a resaltar del resumen de las variables, cabe mencionar que la edad de los participantes en este estudio va desde los 22 años a los 89. Esto, como se menciona en la introducción, es algo relevante a tener en cuenta, ya que conforme la edad aumenta es común aumentar también el porcentaje de grasa.</p>
<ul>
<li><strong>Visualizando las variables en gráficos de cajas y bigotes:</strong></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>Nótese que los individuos con valores anormales del porcentaje de grasa corporal (182 y 172) no destacan realmente en el resto de variables, aunque si que es cierto que presentan valores bajos, en casi todas ellas. Esto nos indica que son individuos con un tamaño corporal pequeño, es decir no son corpulentos.</p>
<p>Se aprecian también valores atípicos, la gran mayoría por exceso, esto no significa que tengamos datos erróneos, sino que nos informa de la presencia de individuos con partes del cuerpo bastante grandes. En principio los atípicos al no ser muchos, no deben de suponer ningún problema para realizar las diferentes técnicas de análisis que emplearemos.</p>
<ul>
<li><p><strong>Escalas de las variables</strong></p>
<p>Aunque en el apartado anterior ya se apreciaba como algunas variables podrían no pertenecer a la misma escala, conviene visualizar el gráfico de cajas y bigotes conjuntamente para todas las variables.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>A simple vista para las variables más hacia la derecha, se aprecia como sí podrían estan dentro de la misma escala. Pero mirando el total del conjunto, se diferencia bastante que tienen escalas distintas.</p>
<p>Por ejemplo, como se muestra en el resumen del apartado anterior, la densidad corporal toma valores en un rango entre 0.995 y 1.109 g/cm3, mientras que de media la circunferencia del pecho es de 100.82 cm, o la de la muñeca es 18.23 cm</p>
<p>Además, si calculamos la desviación estandar de las variables, vemos como las observaciones, se desvían de forma bastante distinta respecto a sus medias, obviando que tienen escalas distintas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>desviaciones_estandar <span class="ot">&lt;-</span> <span class="fu">apply</span>(d, <span class="dv">2</span>, sd)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>desviaciones_estandar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Density     BodyFat         Age      Weight      Height        Neck 
 0.01903143  8.36874041 12.60203972 29.38915989  2.60958292  2.43091323 
      Chest     Abdomen         Hip       Thigh        Knee       Ankle 
 8.43047553 10.78307680  7.16405767  5.24995203  2.41180459  1.69489340 
     Biceps     Forearm       Wrist 
 3.02127375  2.02069117  0.93358493 </code></pre>
</div>
</div>
<p>Por tanto es conveniente estandarizarlas antes de trabajar con ellas.</p>
<p>La estandarización de variables es una práctica bastante común en el análisis de datos que puede mejorar la interpretación, la estabilidad numérica y la comparabilidad de los modelos estadísticos y de aprendizaje automático.</p></li>
<li><p><strong>Relación entre variables:</strong></p>
<p>Resulta conveniente poder conocer si las variables se encuentran bien relacionadas entre sí, o si por el contrario son más independientes.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A primera vista ya vemos como la densidad y la grasa corporal son variables inversamente relacionadas con una correlación notablemente fuerte. También se aprecia cierta relación lineal entre algunas partes del cuerpo, lo que es entendible al ser partes del cuerpo de una misma persona. Sería extraño que un individuo presentase algunas partes del cuerpo anormalmente grandes frente a otras muy pequeñas.</p>
<p>Veamos mas de cerca para algunas variables en concreto:</p>
<p><strong>a).Variables de las medidas corporales:</strong></p>
<p><u>a1. Abdomen y Cintura</u></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(d<span class="sc">$</span>Hip, d<span class="sc">$</span>Abdomen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8740662</code></pre>
</div>
</div>
<p>Se aprecia una fuerte correlación entre la circunferencia del abdomen y la cintura, esto queda explicado claramente al ser partes del cuerpo muy cercanas. Tendrían cuerpos muy descompensados y anormales si presentasen tamaños muy distintos de la cadera y el abdomen.</p>
<p><u>a2. Antebrazo y Muñeca</u></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>En cuanto al antebrazo y la muñeca, la relación sigue siendo notablemente visible, aunque ya no se aprecia tan directa como en el caso del abdomen y la cintura por ejemplo.</p>
<p><u>a3. Tobillo y Cuello</u></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(d<span class="sc">$</span>Ankle, d<span class="sc">$</span>Neck)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4778924</code></pre>
</div>
</div>
<p>En el caso del cuello y el tobillo al ser partes del cuerpo bastante distanciadas, la relación no es tan fuerte.</p>
<p><u>En general las variables que miden el tamaño de partes del cuerpo suelen estar bastante bien relacionadas. Lo cual era de esperar, ya que las partes del cuerpo de una misma persona,</u> salvo por anomalías o casos extremos<u>, tienden a presentan una cierta armonía. Y más aún si son partes del cuerpo pertenecientes a zonas próximas.</u></p>
<p><strong>b).Peso y Altura:</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(d<span class="sc">$</span>Weight, d<span class="sc">$</span>Height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.486888</code></pre>
</div>
</div>
<p>La altura y el peso parecen no guardar una relación tan significativa como la que presentan entre sí las variables que miden el tamaño de miembros del cuerpo. <u>Podemos apreciar como un aumento en el peso no se traduce necesariamente en un aumento de altura.</u></p>
<p><u>Destaca sobretodo el individuo 216</u> por tener un mayor peso que la gran mayoría de hombres del estudio, pero siendo una persona de poca estatura.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Weight Height
216    219     64</code></pre>
</div>
</div>
<p>Mas concretamente este individuo (216) es, el más bajo y pesa más que el 75% de los demás hombres del estudio.</p>
<p><strong>c).Grasa Corporal y Tamaño del Abdomen</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(d<span class="sc">$</span>BodyFat, d<span class="sc">$</span>Abdomen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8134323</code></pre>
</div>
</div>
<p>Esta fuerte correlación entre el aumento de la grasa corporal y el aumento de la circunferencia del abdomen, muy probablemente se deba a que es precisamente en esa parte del cuerpo donde tiende a acumularse la grasa corporal en los hombres.</p>
<p>Si visualizamos la relación entre la grasa corporal y cualquier otra parte del cuerpo, por ejemplo los muslos, vemos como la relación es efectivamente más debil que con el abdomen. Indicando que se agrupa mas tejido graso en el abdomen que en los muslos.</p>
<p>(La línea verde representa la relación entre la grasa corporal y el tamaño abdomen, mientras que la roja la relación entre la grasa corporal y el tamaño del muslo, para así evidenciar que la primera es más fuerte que al segunda)</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>En ambas gráficas destaca el individuo 39 (en rojo), por tener un alto porcentaje de de grasa corporal, pero sobretodo por tener un tamaño corporal bastante por encima del resto de participantes del estudio. Y como por el contrario, obviando a los individuos 182 y 172 que eran los que tenían una medición de la grasa corporal errónea, el 50 (en azul) es uno de los que menos grasa tiene y menor tamaño corporal.</p>
<p><strong>d).Grasa Corporal y Peso:</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>El porcentaje de grasa corporal y el peso, si que guardan relación, aunque no es tan fuerte como en otras variables. Esto puede que se explique ya que, el tejido adiposo que compone la grasa corporal no es tan pesado (0,9 kg/L) como el tejido muscular (1,06 kg/L). Por lo que un <u>aumento de grasa corporal, sí que supondrá un aumento de peso del individuo, pero no tan significativo como un aumento de tejido muscular por ejemplo.</u></p>
<p>(fuente densidad de tejidos : <a href="https://es.wikipedia.org/wiki/Tejido_adiposo#:">https://es.wikipedia.org/wiki/Tejido_adiposo#:\</a>%7B.uri%7D~:text=El%20tejido%20adiposo%20tiene%20una,%2C06%20kg%2FL).</p>
<p><strong>e). Densidad y tamaño del abdomen</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>La firme relación inversa entre la desidad corporal y el tamaño del abdomen puede tener su explicación en unas características anteriormente mencionadas. En un apartado anterior se pode de manifiesto que la fuerte relación entre el tamaño del abdomen y el porcentaje de grasa corporal, se debe a que principalmente la grasa en hombres se acumule en esa zona del cuerpo. Teniendo en cuenta que el tejido adiposo, que conforma la grasa corporal, es menos pesado que el tejido muscular y óseo. Esto da lugar a que un aumento de la grasa corporal, influya proporcionalmente más en un aumento del tamaño del abdomen, que en el peso del individuo.</p>
<p>Siendo la densidad, una magnitud referida a la cantidad de masa en un determinado volumen (m/V), aquellos hombres con mayor porcentaje de grasa corporal presentarán un mayor volumen en proporción a su masa total, que los que preseten un menos grasa corporal.</p>
<p>Lo que se traduce en que, un mayor tamaño del abdomen implica más espacio ocupado en proporción al peso, y por lo tanto menor densidad.</p>
<p><strong>f).Densidad Corporal y Edad</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>También hay variables que son bastante idependientes entre sí como es el caso de la edad con la desidad del cuerpo bajo el agua.</p>
<p>En concluisón, vemos como las variables de las partes del cuerpo, están bastante correladas, lo que puede ser una ventaja o un inconveniente. Debemos tener en cuenta que si se construye un modelo predictivo, hay que tener cuidado al usar variables altamente correlacionadas, ya que pueden llevar a problemas de multicolinealidad.</p>
<ul>
<li><strong>Distribución que siguen las variables</strong></li>
</ul>
<p>Podemos visualizar las variables, con qqnorm() para intentar ver si presentan una distribución normal. Que los datos presenten o no una distribución normal, puede resultar significativo en apartados siguientes de este informe. Si los datos provienen de una distribución normal, los puntos en el gráfico Q-Q estarán aproximadamente a lo largo de la línea recta.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid" width="480"></p>
</div>
</div>
</section>
<section id="análisis-de-las-componentes-principales" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-las-componentes-principales">ANÁLISIS DE LAS COMPONENTES PRINCIPALES</h3>
<p>El Análisis de Componentes Principales (PCA) se emplea para resumir la información contenida en muchas variables aleatorias (relacionadas) y las principales características de sus individuos, en unas pocas variables denominadas componentes principales.</p>
<p>Durante el estudio inicial ya vimos como había algunas variables que no solo empleaban unidades distintas, sino que sus valores se movían en rangos diferentes al resto, es decir que presentaban escalas distintas. A la hora de aplicar un PCA, para evitar que tengan más importancia las variables con escalas mayores, es conveniente que los datos se estandaricen, usando la matriz de correlaciones. De esta forma todas tienen a priori la misma importancia (varianza uno).</p>
<p>Además, para evitar que los individuos con valores de su porcentaje de grasa corporal inferior al mínimo vital (172 y 182), afecten a las interpretaciones de las componentes, es conveniente proseguir el estudio sin ellos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> d[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">172</span>,<span class="dv">182</span>), ]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Para aplicar la matriz de correlaciones el parámetro cor debe tomar valor TRUE</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>PCA <span class="ot">&lt;-</span><span class="fu">princomp</span>(data, <span class="at">cor =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          Comp.1    Comp.2     Comp.3     Comp.4     Comp.5
Standard deviation     2.9829117 1.4250073 1.02025714 0.85648885 0.74891909
Proportion of Variance 0.5931842 0.1353764 0.06939498 0.04890488 0.03739199
Cumulative Proportion  0.5931842 0.7285606 0.79795554 0.84686041 0.88425240
                           Comp.6     Comp.7     Comp.8     Comp.9    Comp.10
Standard deviation     0.70197986 0.54660564 0.50588259 0.47113142 0.43024602
Proportion of Variance 0.03285171 0.01991852 0.01706115 0.01479765 0.01234078
Cumulative Proportion  0.91710411 0.93702263 0.95408378 0.96888143 0.98122221
                           Comp.11     Comp.12     Comp.13     Comp.14
Standard deviation     0.367220531 0.272082302 0.207743256 0.135441922
Proportion of Variance 0.008990061 0.004935252 0.002877151 0.001222968
Cumulative Proportion  0.990212267 0.995147519 0.998024670 0.999247637
                            Comp.15
Standard deviation     0.1062329662
Proportion of Variance 0.0007523629
Cumulative Proportion  1.0000000000</code></pre>
</div>
</div>
<ul>
<li><strong>Selección de las Componentes Principales</strong></li>
</ul>
<p>La importancia de las componentes se mide con las proporciones en tanto por uno de sus varianzas (proportion of Variance) y las proporciones acumuladas.</p>
<p>Para seleccionar cuantas componentes debemos tomar, podemos atender a distintos criterios. Uno de los más comunes es determinar un <u>porcentaje mínimo</u> de variabilidad de la información inicial, que deban abarcar las componentes, y quedarnos con número de componentes suficiente que permita alcanzar ese porcentaje mínimo. Para este caso, un porcentaje de entre el 75 y 80% parece una opción bastante apropiada. Esto sería tomar 3 componentes principales.</p>
<p>Otro critero que se conoce como uno de los más comunes en estadística es <u>la Regla del codo.</u> Esta regla establece que serán representativas las componentes hasta el primer “codo” (sin incluirlo) de la gráfica o hasta que comience la línea recta aproximada final.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>Al visualizar la gráfica vemos claramente un cambio de la tendencia de la pendiente en el punto 2, y otro no tan drástico en torno al punto 3. Lo cual nos está indicando que deberíamos de quedarnos con 1 o 2 componentes.</p>
<p>Un último criterio que empleamos para desempatar es la <u>regla de Kaiser,</u> la cual nos dice que solo serán relevantes las componentes que tengan una variabilidad mayor que la variabilidad media de las variables originales. Al haber usado la matriz de correlaciones, como es equivalente a usar las variables estandarizadas, se entiende que las varianzas iniciales son 1. Entonces solo debemos coger aquellas componentes con una desviación por encima de 1, que en este caso son <u>las 3 primeras.</u></p>
<ul>
<li><strong>Interpretación de las componentes principales:</strong></li>
</ul>
<p>Para dar una interpretación de las componentes debemos mirar las cargas o loadings, que son los vectores propios normalizados. Estos actúan como los coeficientes de las variables iniciales en la expresión que nos permite calcular la componente principal. Por lo tanto como el valor de la componente depende en gran medida de estos coeficientes, los debemos analizar para poder darles un significado.</p>
<section id="i.primera-componente" class="level4">
<h4 class="anchored" data-anchor-id="i.primera-componente">i).Primera componente</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Density     BodyFat         Age      Weight      Height        Neck 
 0.22867862 -0.23436462 -0.01998217 -0.32582490 -0.12824794 -0.28364276 
      Chest     Abdomen         Hip       Thigh        Knee       Ankle 
-0.30477885 -0.30716876 -0.31048270 -0.29231650 -0.28897020 -0.20827228 
     Biceps     Forearm       Wrist 
-0.27886091 -0.22751961 -0.25261922 </code></pre>
</div>
</div>
<p>La expresión de la primera componente principal quedaría como:</p>
<p>Y1 = 0.223 · X1* -0.234· X2* -0.019· X3* -0.326· X4* -0.128· X5* -0.284· X6*- 0.305 · X7*- 0.307 · X8* - 0.31 · X9* -0.292 · X10* - 0.289 · X11* - 0.208 · X12* - 0.279 · X13* - 0.228 · X14*- 0.253 · X15*</p>
<p>En esta componente la variable Edad (Age) no se encuentra bien representada, dado que tiene un valor muy próximo a 0. También nos encontramos con que la variable Altura (Height) tiene una menor relevancia dentro de la componente que el resto de variables (valor absoluto de 0.128, frente a más de 0.200 del resto)</p>
<p>Destaca que las variables de circunferencia corporal (como la del abdomen, cadera, pecho, etc.) tengan una importancia similar dentro de la componente, estando mas o menos igualmente representadas y además están asociadas (negativamente) con la grasa corporal.</p>
<p>La densidad corporal es la única variable que presenta un valor positivo, es decir, esta componente primera es directamente proporcional al aumento de la densidad, mientras que inversamente proporcional al crecimiento del resto de variables como son el aumento de las partes del cuerpo, y el porcentaje de grasa.</p>
<p>Esto sugiere que esta componente es <strong>principalmente un indicativo de las medidas corporales y la densidad y a su vez de como influye la distribución de la grasa corporal en el tamaño de partes del cuerpo.</strong></p>
<p>Entonces presentará <u>valores pequeños cuanto más corpulento sea el indivividuo, y valores grandes cuanto menor tamaño corporal y menos porcentaje de grasa tenga (porque será más denso).</u></p>
</section>
<section id="ii.segunda-componente" class="level4">
<h4 class="anchored" data-anchor-id="ii.segunda-componente">ii).Segunda Componente</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Density     BodyFat         Age      Weight      Height        Neck 
 0.43571583 -0.43181978 -0.45715038  0.07818553  0.46272675  0.03852264 
      Chest     Abdomen         Hip       Thigh        Knee       Ankle 
-0.12508748 -0.21154452  0.03289539  0.09983137  0.12567210  0.24129140 
     Biceps     Forearm       Wrist 
 0.08940282  0.15797226  0.12072463 </code></pre>
</div>
</div>
<p>En esta segunda componente principal no están bien representadas ni el Peso (Weight), ni el tamaño del Cuello (Neck), Cadera (Hip) y Biceps. Además, el resto de variables relacionadas con la circunferencia de partes del cuerpo, no presentan una influencia excesivamente significativa.</p>
<p>Mientras que, las variables con los loadings más altos y por tanto fuertemente relacionadas con la componente son, la Densidad corporal, la Altura, el porcentaje de Grasa corporal y la Edad. Teniendo la Densidad y la Altura coeficientes positivos y la Grasa y la Edad, coeficientes negativos, además de encontrarse prácticamente igual representadas.</p>
<p>Cabe destacar que la Densidad y Grasa Corporal, están estrechamente relacionadas entre sí, como se expone en apartados anteriores, dado que un aumento de la grasa corporal supone un cambio más significativo en el volumen del cuerpo, que en el peso total de este, propiciando disminución de la densidad. O viéndolo desde otro enfoque, una alta densidad indica una mayor proporción de masa magra en comparación con la grasa corporal. Esto concuerda con que estén contrarrestándose entre sí en la componente (distinto signo).</p>
<p>Por otro lado, la edad y la altura son factores que influyen en la composición y estructura corporal. La edad podría representar el efecto del envejecimiento en el cuerpo, como señalábamos en la introducción. Y la altura (comúmente usada en otros campos como un indicador de la estructura corporal), podría estar relacionada con la distribución de la masa corporal, de forma que una altura mayor, pueda significar una distribución diferente de la grasa y la masa magra, dando lugar a tamaños diferentes de las distintas partes del cuerpo.</p>
<p>Por lo tanto, esta segunda componente principal representa <strong>la variabilidad en la composición corporal</strong> (más tejido muscular o graso), <strong>y la influencia de la edad y la altura en esta composición.</strong></p>
<p>Un <u>valor alto de la componente indicará alta densidad, gran altura y un porcentaje de grasa corporal bajo, mientras que valores bajos, lo contrario, es decir, poca densidad y alto porcentaje de grasa corporal.</u></p>
</section>
<section id="iii.tercera-componente" class="level4">
<h4 class="anchored" data-anchor-id="iii.tercera-componente">iii).Tercera Componente</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Density     BodyFat         Age      Weight      Height        Neck 
 0.23447893 -0.21230415  0.68454730 -0.02289917  0.11309620  0.21349615 
      Chest     Abdomen         Hip       Thigh        Knee       Ankle 
 0.04106378 -0.03565554 -0.16389951 -0.29770763  0.02067445  0.08862080 
     Biceps     Forearm       Wrist 
-0.02616623  0.07843375  0.48875128 </code></pre>
</div>
</div>
<p>En esta componente las circunferencias de las partes del cuerpo no son muy significativas, estando la mayoría poco representadas al tener coeficientes cercanos a 0.</p>
<p>También vuelve a darse en esta componente, aunque de una forma menos destacada, la relación inversa entre la densidad corporal y el porcentaje de grasa, que explicabamos para la componente anterior.</p>
<p>Y sobretodo tiene una altísima relevancia la variable Edad. Por lo que esta componente <strong>es principalmente un indicativo de la edad del varón</strong>. De la forma que <u>tomará valores mas altos, para aquellos individuos más longevos.</u></p>
<ul>
<li><strong>Puntuaciones de los Individuos para las componentes principales</strong></li>
</ul>
<p>Estas puntuaciones nos permiten tener una imagen de como son los individuos, segun los valores que toman en esa componente</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>S <span class="ot">&lt;-</span> PCA<span class="sc">$</span>scores</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Podemos analizar, algunos de los individuos con puntuaciones más extremas en las componentes.</p>
<p>Por ejemplo para la componente primera, el individuo con la menor puntuación es el 39.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(S[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>39 
39 </code></pre>
</div>
</div>
<p>Recordemos que tener una puntuación baja en esta componente estaba relacionado con tener un gran tamaño de las partes del cuerpo, y además una gran porcentaje de acumulación de grasa.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Density BodyFat Age Weight Height Neck Chest Abdomen   Hip Thigh Knee Ankle
39  1.0202    35.2  46 363.15  72.25 51.2 136.2   148.1 147.7  87.3 49.1  29.6
   Biceps Forearm Wrist
39     45      29  21.4</code></pre>
</div>
</div>
<p>Efectivamente, viendo los valores de este individuo 39 en las variables inicales, denota un tamaño corporal por encima de la media. Por ejemplo, la cintura de media tiene 99.9 cm de circunferencia y la de este hombre son 147.7 cm, o su peso es de 363 libras que equivale a unos 160 kg.</p>
<p>Por el contrario, mirando al individuo con mayor puntuación en la primera componente, el 45. Se diferencia del 39, al presentar un tamaño corporal pequeño, y bajo porcentaje de grasa, llevando a su vez a una densidad mayor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(S[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>45 
45 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Density BodyFat Age Weight Height Neck Chest Abdomen  Hip Thigh Knee Ankle
45  1.0814     7.7  39 125.25     68 31.5  85.1      76 88.2    50 34.7    21
   Biceps Forearm Wrist
45   26.1    23.1  16.1</code></pre>
</div>
</div>
<p>También podemos hacer lo propio para la componente segunda:</p>
<p>El individuo con la máxima puntuación en la componente seguda es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(S[,<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>12 
12 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Density BodyFat Age Weight Height Neck Chest Abdomen   Hip Thigh Knee Ankle
12  1.0812     7.8  27    216     76 39.4 103.6    90.9 107.7  66.2 39.2  25.9
   Biceps Forearm Wrist
12   37.2    30.2    19</code></pre>
</div>
</div>
<p>Tener una puntuación alta en esta segunda componente era sinónimo de una densidad alta, gran altura y bajo porcentaje de grasa corporal. Vemos como efectivamente este individuo 12 con la máxima puntuación, tiene una altura de 76 pulgadas que son 193 cm, un bajo porcentaje de grasa corporal, y además, presenta alta densidad (el 75% de los hombres del estudio tiene una densidad inferior a 1.07 g/cm3) .</p>
<p>Finalmente, podemos analizar los siguientes gráficos que muestran las puntuaciones de los individuos para las dos primeras componentes principales.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En el primer gráfico (izquierda), los individuos con tamaño corporal pequeño y poca acumulación de grasa se encuentran más hacia la derecha (en la componente primera), como es el caso del 45, y aquellos con mayor altura y densidad se encuentran más arriba (en la componnete segunda), como es el caso del individuo 12.</p>
<p>El segundo gráfico (derecha) es similar al primero, pero las variables aparecen como vectores en rojo y las puntuaciones estandarizadas como las etiquetas de los datos en negro. En este, las variables presentan vectores largos, lo que es sinónimo de que se encuentran bien representadas por las dos primeras componentes. Si tuvieran vectores cortos , es indicativo de que la información se pierde al ser proyectada, por ser casi perpendiculares, lo que sería sintoma de estar mal representadas.</p>
<p>Con este segundo gráfico se comprueba la interpretación hecha al gráfico anterior, al ver al individuo 45, que presentaba un tamaño corporal pequeño, en dirección contraria a los vectores de las variables que tasan el tamaño de partes del cuerpo. O al individuo 39, que se caracteriza por tener un tamaño corporal atípicamente grande, estando muy hacia la izquierda, donde confluyen la mayoría de vectores de las variables que miden el tamaño de partes del cuerpo.</p>
<p>Una vez tenemos las puntuaciones de todos los individuos y para todas las componentes, debemos tomar únicamente las puntuaciones de aquellas con las que elegimos quedarnos, (1,2y 3). De esta forma podríamos emplearlas, según convenga, para futuras técnicas que llevemos a cabo, en vez de utilizar las 15 variables de nuestro dataset original.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Puntuaciones3Comp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Comp1 =</span> S[,<span class="dv">1</span>], <span class="at">Comp2 =</span> S[,<span class="dv">2</span>], <span class="at">Comp3 =</span> S[,<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Saturaciones</strong></li>
</ul>
<p>Para poder conocer la información total que se tiene de cada variable en las componentes debemos calcular las saturaciones al cuadrado. Estas nos indicarán cuanta información (en tanto por 1) habrá en cada componente de cada variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>SAT<span class="ot">&lt;-</span><span class="fu">cor</span>(data,S)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Además para conocer el porcentaje total de cada variable entre las 3 componentes con las que nos hemos quedado, debemos calcular las comunalidades. En nuestro caso, se calculan como la suma de las saturaciones al cuadrado de las 3 componentes principales.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>COMUNALIDADES</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Inf. Comp1  Inf. Comp2    Inf Comp3 Comunalidad
Density 0.465298806 0.385514637 0.0572304204   0.9080439
BodyFat 0.488725417 0.378651128 0.0469176521   0.9142942
Age     0.003552763 0.424377509 0.4877824890   0.9157128
Weight  0.944603070 0.012413291 0.0005458318   0.9575622
Height  0.146346244 0.434793869 0.0133142069   0.5944543
Neck    0.715853581 0.003013466 0.0474459751   0.7663130
Chest   0.826514458 0.031773266 0.0017552427   0.8600430
Abdomen 0.839527441 0.090873601 0.0013233460   0.9317244
Hip     0.857739928 0.002197375 0.0279624084   0.8878997
Thigh   0.760304363 0.020238029 0.0922569746   0.8727994
Knee    0.742996794 0.032070957 0.0004449254   0.7755127
Ankle   0.385961288 0.118227326 0.0081750532   0.5123637
Biceps  0.691920319 0.016230677 0.0007126916   0.7088637
Forearm 0.460594231 0.050675243 0.0064036157   0.5176731
Wrist   0.567823797 0.029595520 0.2486538023   0.8460731</code></pre>
</div>
</div>
<p>Entre las 3 componentes, el porcentaje de información que recogen en general de cada variable es bastante alto, superando el 80%, en la mayoría de casos. Auque las variables Ankle y Forearm, son de las que peor porcentaje de información se conserva, superando levemente el 50 %.</p>
</section>
</section>
<section id="análisis-clúster-aprendizaje-no-supervisado" class="level3">
<h3 class="anchored" data-anchor-id="análisis-clúster-aprendizaje-no-supervisado">ANÁLISIS CLÚSTER: APRENDIZAJE NO SUPERVISADO</h3>
<p>En el gráfico que se visualizó de las puntuciones de los individuos respesto a las dos primeras componentes principales, vimos como una mayoría tendía a agruparse hacia la derecha y en torno al centro del gráfico, mientras que había otros individuos que se localizaban en posiciones más alejadas de esta agrupación principal, lo cual sugiere, que muy probablemente, podamos distinguir a los individuos de este estudio entre grupos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Intetaremos agrupar a los individuos del dataset según la similitud de sus valores en las variables. Al no existir grupos iniciales, este tipo de técnica se denominan análisis no supervisado o aprendizaje automático. La formación de los grupos dependerá de las distancias usadas para medir las similitudes y del algoritmo de agrupación aplicado.</p>
<p>Existen principalmente dos algoritmos para llevar a cabo la clasificación de los individuos, K-means (análisis cluster con k-means) y h-clust (análisis cluster jerarquizado). Para el primer algoritmo es necesario indicar inicialmente el número de grupos o clusters entre los que agrupar. Mientras que para el segundo no es necesario.</p>
<p>En nuestro caso, a partir del estudio anterior realizado, <strong>no es sencillo determinar a simple vista un número concreto de grupos en el que estarían repartidos los individuos del dataset,</strong> por lo que aplicaremos el <strong>análisis jerarquizado por h-clust</strong>. Con este algortimo, un dendrograma nos indicará los grupos que se van formando y nos permitirá decidir con cuántos nos quedamos.</p>
<p>El funcionamiento de este algoritmo se basa en calcular las distancias de cada uno de los individuos a todos los demás, e ir agrupando iteración por iteración a las observaciones que más cercanas se encuentren entre sí. Cada individuo forma un cluster inicialmente, y con que se agrupen dos observaciones, ya tendremos un nuevo cluster, que se irá ampliando con las demás observaciones o clusters similares que tengan una distancia cercana.</p>
<p>La idea es poder distinguir entre varias clases que se diferencien según el tipo de cuerpo del individuo y su composición/estructura.</p>
<p>Este análisis cluster podría llevarse a cabo solo con los datos de las puntuciones de los individuos en las 3 primeras componentes pricipales que recopilamos anteriormente, sin embargo dado que el número de variables iniciales no es muy alto (15), lo haremos también con las variables originales, permitiéndonos clasificar a los individuos antendiendo al 100% de la información total. Y pudiendo comparar resultados.</p>
<section id="aplicación-del-análisis-jerarquizado-hclust-al-dataset-original" class="level4">
<h4 class="anchored" data-anchor-id="aplicación-del-análisis-jerarquizado-hclust-al-dataset-original"><strong>1.Aplicación del análisis jerarquizado (hclust) al dataset original</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ds <span class="ot">&lt;-</span> <span class="fu">scale</span>(data) <span class="co">#Estandarizar los datos: Ya se introdujo en apartados anteriores la importancia de estandarizar los datos.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>Distancias <span class="ot">&lt;-</span> <span class="fu">dist</span>(ds, <span class="at">method =</span> <span class="st">'euclidean'</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Aplicamos la distancia euclídea</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>CA <span class="ot">&lt;-</span> <span class="fu">hclust</span>(Distancias, <span class="at">method =</span> <span class="st">"complete"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El dendograma nos muestra como se han ido formando las distintas agrupaciones, y nos permite decidir a simple vista en cuantas clases posibles podríamos dividir a los individuos del dataset.</p>
<p>Debido al gran número de individuos resulta dificil diferenciar a simple vista los dos individuos que primero se agruparon, pero sacándolo por medio de la matriz de distancias, vemos que se trata de los individuos 225 y 228.</p>
<p>Sí que está muy claro que el último en ser agrupado fue el 39, lo cual indica claramente su tamaño atípicamente grande respecto al resto de participantes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(Distancias)[<span class="dv">1</span><span class="sc">:</span><span class="dv">250</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">250</span>]</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(Distancias)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8553559</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Encontrar la posición del valor en la matriz</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>posicion <span class="ot">&lt;-</span> <span class="fu">which</span>(M <span class="sc">==</span> <span class="fu">min</span>(Distancias), <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir la fila y la columna donde se encuentra el valor</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Fila:"</span>, posicion[,<span class="dv">1</span>], <span class="st">"Columna:"</span>, posicion[,<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Fila: 228 Columna: 225" "Fila: 225 Columna: 228"</code></pre>
</div>
</div>
<p><strong>1.1Número de grupos a escoger</strong></p>
<p>Mirando el dendrograma, parece una buena opción tener entre 4 y 5 grupos. Realmente no existe un número óptimo, sino que es algo que depende en gran medida de factores subjetivos, pero existen técnicas que pueden ayudarnos a decidir.</p>
<p>Hay índices implementados en R que nos pueden ayudar a decidirnos por un número de grupos en concreto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(NbClust)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">NbClust</span>(ds,<span class="at">method=</span><span class="st">'complete'</span>,<span class="at">index=</span><span class="st">'all'</span>)<span class="sc">$</span>Best.nc</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Escondo el resultado para evitar ocupar innecesariamente espacio</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-47-2.png" class="img-fluid" width="384"></p>
</div>
</div>
<p>En nuestro caso, se indica que hay una mayoría de 9 índices que determinan que el mejor el número de clusters es 5, aunque también hay un segundo conjunto de 8 índices que determinan el óptimo en 2 clusters.</p>
<p>Agrupamos por tanto en 5 clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Agrupando en 5 grupos</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>g5 <span class="ot">&lt;-</span> <span class="fu">cutree</span>(CA, <span class="at">k =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos como el atípico 39, da lugar a la creación de un grupo para poder clasificarlo únicamente a él. Esto a la hora de llevar a cabo algunas técnicas como análisis discriminante, puede suponer un grave desbalanceo que afecte gravemente a las conclusiones que se obtengan. Por lo tanto debemos evaluar realmente la relevancia del atípico en el análisis, ¿Es un error de medición o un punto realmente significativo?</p>
<p>Realmente este indivividuo 39 no es un error de medición, sino que simplemente es alguien que presenta un tamaño corporal bastante superior a lo común. Esto es algo perfectamente posible en la realidad.</p>
<p>Sin embargo, este grupo de un único individuo quizás esté distorsionando los resultados, por lo que para hacer un correcto análisis cluster resulta conveniente excluirlo del dataset a la hora de clasificar. Por ello vamos a repetir el proceso sin el atípico 39.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al eliminar el atípico 39, ya no se refleja en el dendrograma. A simple vista sigue pareciendo buena idea la clasificación entre 4 y 5 grupos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>*** : The Hubert index is a graphical method of determining the number of clusters.
                In the plot of Hubert index, we seek a significant knee that corresponds to a 
                significant increase of the value of the measure i.e the significant peak in Hubert
                index second differences plot. 
 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-51-2.png" class="img-fluid" width="384"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>*** : The D index is a graphical method of determining the number of clusters. 
                In the plot of D index, we seek a significant knee (the significant peak in Dindex
                second differences plot) that corresponds to a significant increase of the value of
                the measure. 
 
******************************************************************* 
* Among all indices:                                                
* 7 proposed 2 as the best number of clusters 
* 3 proposed 3 as the best number of clusters 
* 8 proposed 4 as the best number of clusters 
* 3 proposed 5 as the best number of clusters 
* 2 proposed 15 as the best number of clusters 

                   ***** Conclusion *****                            
 
* According to the majority rule, the best number of clusters is  4 
 
 
******************************************************************* </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     KL     CH Hartigan     CCC    Scott      Marriot   TrCovW
Number_clusters  4.0000  2.000   4.0000  4.0000   5.0000 5.000000e+00     3.00
Value_Index     12.2447 78.632  56.7381 -7.7777 255.9707 4.392002e+26 17195.03
                  TraceW Friedman   Rubin Cindex     DB Silhouette   Duda
Number_clusters   4.0000   3.0000  4.0000 2.0000 2.0000     2.0000 4.0000
Value_Index     417.7671  30.3161 -0.3272 0.3183 1.2626     0.2186 0.8964
                PseudoT2  Beale Ratkowsky     Ball PtBiserial Frey McClain
Number_clusters   4.0000 4.0000    2.0000   3.0000     5.0000    1  2.0000
Value_Index      13.1821 1.1839    0.3412 551.5849     0.4863   NA  0.3481
                   Dunn Hubert SDindex Dindex   SDbw
Number_clusters 15.0000      0  2.0000      0 15.000
Value_Index      0.2592      0  1.3628      0  0.386</code></pre>
</div>
</div>
<p>Sin el atípico, un mayoría de 8 índices indican 4 como el mejor número de clusters. Lo que concuerda con el resto de grupos que no estaban formados por un atípico.</p>
<p>Agrupando en 4 clusters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> <span class="fu">cutree</span>(CA, <span class="at">k =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El algoritmo hclust ha hecho la misma clasificación que antes de eliminar el atípico, lo cual es lógico ya que las distancias entre los distintos individuos sigue siendo la misma a pesar de considerar un individuo menos.</p>
<p>Debemos recopilar la agupación hecha como un único dataset para su posterior uso:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos dos dataset nuevos para guardar la clasificación de los datos sin el atípico 39, para evitar así eliminarlo del todo por si nos puede servir en algún paso siguiente.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>dataClasified <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(data[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">39</span>),],g4)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>dsClasified <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ds[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">39</span>),],g4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>1.2 Descripción de los grupos.</strong></p>
<p>Si llevamos a cabo un breve estudio de las características de los grupos nos va a permitir describirlos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-56-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-56-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-57-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Atendiendo al resumen de las variables respecto a cada grupo y a las anteriores gráficas podemos describir los grupos en los que se clasifican a los individuos de la siguiente forma:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p><span class="smallcaps">Grupo1</span>. (Negro): De media es el grupo con más densidad, y que menor porcentaje de grasa corporal presenta. Además sus individuos tienen el menor peso corporal. Y en cuanto al tamaño, son los individuos con menor circunferencia de las partes del cuerpo. En conclusión, son los <strong>hombres menos corpulentos y con el menor porcentaje de grasa corporal.</strong></p>
<p><span class="smallcaps">Grupo2. (Rojo):</span>Los individuos de este grupo presentan un porcentaje de grasa corporal repartido, con valores tanto altos como bajos, pero con una mayoría de individuos con un porcentaje moderado o no muy alto , entre el 17 y el 20 %, y un peso corporal medio/bajo. El tamaño de las distintas partes del cuerpo es en general también intermedio o medio/bajo, pero por encima de los individuos del primer grupo. Se puede resumir en <strong>individuos con un tamaño corporal medianamente pequeño (medio/bajo), y con un porcentaje de grasa mayoritariamente moderado.</strong></p>
<p><span class="smallcaps">Grupo3</span>. (Verde) En este grupo los individuos presentan un porcentaje de grasa corporal bastante repartido al igual que en el grupo 2, pero mayoritariamente algo mayor, en un rango medio/alto , en torno al 22 - 24%. Presentan un peso corporal más bien alto, junto con un tamaño corporal medio/alto. En conclusión, son <strong>hombres con un tamaño corporal medianamente grande, y porcentaje de grasa corporal mediano. Destacan también por ser mayoritariamente el grupo de hombres más altos.</strong></p>
<p><span class="smallcaps">Grupo4</span>. (Azul oscuro): Grupo formado por un conjunto reducido de individuos que presentan porcentajes altos de grasa, junto con un alto peso corporal. Siendo a su vez el grupo con la densidad corporal más baja en general. Destacan por tener un tamaño corporal bastante mayor que el resto de individuos. Podría resumirse como el grupo de <strong>los</strong> <strong>hombres más corpulentos, y de mayor porcentaje de grasa corporal, además de un peso corporal pesado.</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 1:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 2"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 116</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 3"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 70</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 4"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
</div>
<p>Se da claramente un desbalanceo al haber un número total de individuos tan dispar en cada grupo. Es importante tener esto en cuenta ya que al realizar algunos análisis estadísticos puede conducir a resultados sesgados o poco confiables.</p>
</section>
<section id="aplicación-del-análisis-jerarquizado-hclust-a-partir-de-las-puntuaciones-de-los-individuos-en-las-3-componentes-principales" class="level4">
<h4 class="anchored" data-anchor-id="aplicación-del-análisis-jerarquizado-hclust-a-partir-de-las-puntuaciones-de-los-individuos-en-las-3-componentes-principales"><strong>2.Aplicación del análisis jerarquizado (hclust) a partir de las puntuaciones de los individuos en las 3 componentes principales</strong></h4>
<p>Durante el Análisis de las componentes principales, seleccionamos las 3 primeras que abarcaban un porcentaje total de la información del 80%, esto quiere decir que muy probablemente la clasificación que obtengamos en este segundo análsis cluster varíe, siendo menos precisa.</p>
<p>Obtenemos el siguiente dendrograma:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Parece que lo mejor sería tomar entre 2 y 4 grupos.</p>
<p><strong>2.1Número de grupos a escoger</strong></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>*** : The Hubert index is a graphical method of determining the number of clusters.
                In the plot of Hubert index, we seek a significant knee that corresponds to a 
                significant increase of the value of the measure i.e the significant peak in Hubert
                index second differences plot. 
 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-61-2.png" class="img-fluid" width="480"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>*** : The D index is a graphical method of determining the number of clusters. 
                In the plot of D index, we seek a significant knee (the significant peak in Dindex
                second differences plot) that corresponds to a significant increase of the value of
                the measure. 
 
******************************************************************* 
* Among all indices:                                                
* 7 proposed 2 as the best number of clusters 
* 6 proposed 3 as the best number of clusters 
* 3 proposed 4 as the best number of clusters 
* 2 proposed 6 as the best number of clusters 
* 1 proposed 10 as the best number of clusters 
* 2 proposed 12 as the best number of clusters 
* 2 proposed 15 as the best number of clusters 

                   ***** Conclusion *****                            
 
* According to the majority rule, the best number of clusters is  2 
 
 
******************************************************************* </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    KL       CH Hartigan     CCC    Scott   Marriot   TrCovW
Number_clusters 12.000   2.0000   3.0000  2.0000   4.0000         6      4.0
Value_Index     10.322 159.6128  67.7747 -7.2497 163.9422 457674717 219365.9
                  TraceW Friedman   Rubin Cindex     DB Silhouette   Duda
Number_clusters   4.0000  12.0000  6.0000 2.0000 3.0000     2.0000 2.0000
Value_Index     315.1699   3.1969 -0.4396 0.2223 0.7706     0.3882 1.0608
                PseudoT2   Beale Ratkowsky     Ball PtBiserial Frey McClain
Number_clusters   2.0000  2.0000   10.0000   3.0000      3.000    1  3.0000
Value_Index      -3.0962 -0.0958    0.2241 346.8593      0.538   NA  0.3022
                   Dunn Hubert SDindex Dindex    SDbw
Number_clusters 15.0000      0  3.0000      0 15.0000
Value_Index      0.0978      0  1.1507      0  0.1187</code></pre>
</div>
</div>
<p>En este caso la mayoría de índices indican que el mejor número de clusters es 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Agrupando en 2 grupos</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">cutree</span>(CA2, <span class="at">k =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finalmente añadimos la clasificación hecha a los dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Le quito el 39 porque así lo había hecho en los dos dataset anteriores</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>Puntuaciones3Comp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Puntuaciones3Comp[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">39</span>),],g2)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>dataClasified <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(dataClasified, g2)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>dsClasified <span class="ot">&lt;-</span><span class="fu">data.frame</span>(dsClasified,g2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>2.2 Descripción de los grupos.</strong></p>
<p>Al existir solamente dos grupos, el estudio de las características de estos se simplifica bastante.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-67-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-67-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Con tan solo dos grupos, la clasificación queda algo pobre, al no ser tan precisa como la anterior hecha con 4 grupos.</p>
<p>En este caso tenemos un primer grupo (en color negro en la gráfica) en el que se clasifican los hombres con un porcentaje de de grasa tanto pequeño como intermedio, peso corporal entre pequeño y mediano, mayor densidad y con un tamaño corporal tanto pequeño como intermedio, es decir no excesivamente corpulentos. Y un segundo grupo que aglutina a aquellos con un mayor peso corporal, porcentaje de grasa alto, menor densidad y los más corpulentos.</p>
<p><span class="smallcaps">Grupo1.</span> Los <strong>hombres con un tamaño corporal tanto pequeño como mediano y un porcentaje graso entre bajo y medio.</strong></p>
<p><span class="smallcaps">Grupo2</span>. Los <strong>hombres que destacan por tener una mayor corpulencia y porcentaje de grasa que el resto.</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 1:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 194</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 2"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55</code></pre>
</div>
</div>
</section>
<section id="cómo-hubiera-clasificado-el-algoritmo-kmeans-para-el-mismo-número-de-grupos" class="level4">
<h4 class="anchored" data-anchor-id="cómo-hubiera-clasificado-el-algoritmo-kmeans-para-el-mismo-número-de-grupos"><strong>3.¿Cómo hubiera clasificado el algoritmo kmeans para el mismo número de grupos?</strong></h4>
<p>Finalemente podemos comparar la clasificación en 4 grupos hecha por hclust con la que haría Kmeans</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-69-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Añadimos la clasificación a los dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> CA1<span class="sc">$</span>cluster</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>dataClasified <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(dataClasified, Y)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>dsClasified <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(dsClasified,Y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>3.2 Descripción de los grupos.</strong></p>
<p>Visualizamos las variables respecto a los grupos formados por kmeans, lo que nos permite describir las caracaterísticas de estos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-72-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-72-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-72-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La clasficación por el algortimo kmeans es distinta a la hecha anteriormente con hclust. Esto se debe a que kmeans, como primer paso determina los centroides iniciales de los k grupos al azar, agrupando a los individuos según su cercanía a estos centroides (de ahí la semilla). Lo que da lugar a que aunque los centroides se vuelvan a calcular tras cada iteración, haya una componente de aleatoriedad en este algoritmo y quizás para un conjunto de datos pequeño como este, en el que los grupos no están tan bien definidos, no sea tan preciso. Además de que puede dar lugar a una peor clasificación, dado que se vea forzado a incluir algún atípico en un grupo, teniendo que desplazar o modificar los ‘límites’ de otros grupos.</p>
<p><u>-Una descripción de los grupos hecha por kmeans sería:</u></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-73-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p><span class="smallcaps">Grupo1</span>. (Verde): Es un grupo en el que sus individuos presentan un <strong>porcentaje de grasa corporal intermedio, junto con un tamaño corporal mediano y estatura entre media y baja.</strong></p>
<p><span class="smallcaps">Grupo2. (Naranja):</span> Se trata del grupo que engloba a los <strong>hombres de mayor tamaño corporal, así como un porcentaje de grasa mayoritariamente más alto</strong> que el resto de grupos, también presentan <strong>gran estatura.</strong></p>
<p><span class="smallcaps">Grupo3</span>. (Azul): En este grupo los individuos presentan un <strong>porcentaje de grasa corporal medio/bajo</strong>, con un <strong>tamaño corporal mediano</strong>, pese a ser los <strong>individuos mayoritariamente más altos.</strong> Además tienen un <strong>peso corporal medio bajo.</strong></p>
<p><span class="smallcaps">Grupo4</span>. (Rosa): Este grupo lo componen los <strong>hombres de menor tamaño y peso corporal</strong>, que además presentan el <strong>menor porcentaje de grasa</strong> corporal.</p>
<p>Para esta nueva clasificación, tenemos <u>dos grupos que engloban a los individuos de mayor y menor tamaño corporal,</u> estos son el 2 y el 4, cuyas características se asemejan a las de los grupos 4 y 1 del hclust respectivamente. Y además, <u>se tiene dos cluster para aquel subconjunto de hombres con una corpulencia intermedia, pero que se diferencian mayoritariamente por su edad y altura.</u></p>
<p>Siendo estos últimos los cluster 1 y 3. Son bastante similares, presentando ambos un tamaño corporal mediano/pequeño, pero el primero de ellos destacando por componerse de indviduos más longevos y de menor estatura, mientras que el otro por tener individuos más jovenes, más altos y con un porcentaje de grasa corporal algo más bajo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 1:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 2"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 3"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Individuos del grupo 4"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59</code></pre>
</div>
</div>
<p>Con kmeans sigue habiendo un problema de desbalanceo, pero este se reduce bastante.</p>
<hr>
<p>En coclusión, con <strong>hclust los grupos son más representativos, los individuos quedan mejor delimitados según sus atributos corporales</strong> <strong>que con kmeans</strong> permitiéndonos definir/describir mejor las características de estos. <strong>Pero con kmeans se da un menor balanceo lo que pueda repercutir en resultados más fiables a la hora de clasificar nuevos individuos.</strong></p>
<hr>
</section>
</section>
<section id="análisis-discriminante" class="level3">
<h3 class="anchored" data-anchor-id="análisis-discriminante">ANÁLISIS DISCRIMINANTE</h3>
<p>Con tal de <u>validar si los grupos obtenidos anteriormente por análisis cluster son realmente distinguibles, así como, cual de las dos algoritmos obtiene resultados más precisos (hclust o kmeans) y además descubrir qué variable es la más influyente a la hora de clasificarlos</u>, vamos a llevar a cabo un análisis discriminante.</p>
<p>Aplicamos el análisis discriminante con las variables estandarizadas, ya que de esta forma tendrán valores similares, y así los coeficientes obtenidos con ellas en el análisis se podrán usar para estudiar la influencia de las variables en la clasificación.</p>
<ul>
<li><strong>¿LDA o QDA?</strong></li>
</ul>
<p>Primeramente debemos intentar decidir qué método es el óptimo para nuestros datos. En función de las características de estos debemos determinar cual de los dos métodos, LDA o QDA, podría retornar mejores resultados.</p>
<p>Será buena opción aplicar LDA si las matrices de covarianzas de cada grupo son iguales o muy similares, mientras que la opción del QDA será más acertada si las variables usadas para clasificar son normales (multivariantes) en cada grupo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'MASS'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'mvnormtest'</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Comprobando para el LDA</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>grupo1 <span class="ot">&lt;-</span> dsClasified[dsClasified<span class="sc">$</span>g4 <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>]</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(grupo1)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>grupo2 <span class="ot">&lt;-</span> dsClasified[dsClasified<span class="sc">$</span>g4 <span class="sc">==</span> <span class="dv">2</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>]</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">cov</span>(grupo2)</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>grupo3 <span class="ot">&lt;-</span> dsClasified[dsClasified<span class="sc">$</span>g4 <span class="sc">==</span> <span class="dv">3</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>]</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> <span class="fu">cov</span>(grupo3)</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>grupo4 <span class="ot">&lt;-</span> dsClasified[dsClasified<span class="sc">$</span>g4 <span class="sc">==</span> <span class="dv">4</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>]</span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> <span class="fu">cov</span>(grupo4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>**Véase, en el archivo de código aportado, como las matrices de covarianzas no coinciden, son bastante diferentes. No se adjunta la salida de las matrices al ocupar mucho espacio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Comprobación del QDA.</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(grupo1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.15653, p-value = 4.177e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(grupo2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.22405, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(grupo3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.13549, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(grupo4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.41345, p-value = 7.607e-07</code></pre>
</div>
</div>
<p>Tampoco pasan el test de normalidad para poder confirmar la aplicación del QDA.</p>
<p>Por ello, viendo que ninguna de las dos comprobaciones, ni la del LDA, ni la del QDA, se cumple, podemos optar por emplear ambas y quedarnos con la que mejor clasifique los datos.</p>
<p><strong><code>1.LDA</code></strong></p>
<p>La función para aplicar el LDA presenta un parámetro ‘prior’, que permite definir las probabilidades de perternecia a priori a cada clase. Se suele emplear cuando se conocen dichas probabilidades y son fáciles de expresar. En este caso, al estar tan desbalanceados los grupos es preferible que no se fije ninguna probabilidad a priori, de forma que se estime automáticamente utilizando la proporción de observaciones en cada clase en los datos de entrenamiento.</p>
<p>Además, <u>el análisis se lleva a cabo por validación cruzada</u>, de forma que no tengamos que diferenciar entre dos conjuntos de test o entrenamiento, sino que es la propia función la que hace particiones de todo el conjunto de datos y va tomando por cada iteración todas las particiones menos una, para dedicarlas a entrenamiento y la que excluyó la emplea para testear. Esta es una práctica común cuando la muestra no es de gran tamaño.</p>
<ul>
<li><strong>Análisis discriminante lineal para la clasificación hecha por hclust</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>LDACV<span class="ot">&lt;-</span><span class="fu">lda</span>(dsClasified[,<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>],dsClasified<span class="sc">$</span>g4,<span class="at">CV=</span><span class="cn">TRUE</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>matrizConfusion1<span class="ot">&lt;-</span><span class="fu">table</span>(dsClasified<span class="sc">$</span>g4,LDACV<span class="sc">$</span>class,<span class="at">dnn=</span><span class="fu">c</span>(<span class="st">"real"</span>,<span class="st">"predicho"</span>))</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>matrizConfusion1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    predicho
real   1   2   3   4
   1  40   8   0   0
   2   7 104   4   1
   3   0   9  57   4
   4   0   0   5  10</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>accuracy1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(matrizConfusion1)) <span class="sc">/</span> <span class="fu">sum</span>(matrizConfusion1)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>accuracy1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8473896</code></pre>
</div>
</div>
<ul>
<li><strong>Análisis discriminante lineal para la clasificación hecha por Kmeans</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>LDACV2<span class="ot">&lt;-</span><span class="fu">lda</span>(dsClasified[,<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>],dsClasified<span class="sc">$</span>Y,<span class="at">CV=</span><span class="cn">TRUE</span>)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>matrizConfusion2<span class="ot">&lt;-</span><span class="fu">table</span>(dsClasified<span class="sc">$</span>Y,LDACV2<span class="sc">$</span>class, <span class="at">dnn=</span><span class="fu">c</span>(<span class="st">"real"</span>,<span class="st">"predicho"</span>))</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>matrizConfusion2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    predicho
real  1  2  3  4
   1 77  0  1  3
   2  1 53  1  0
   3  8  4 41  1
   4  4  0  0 55</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>accuracy2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(matrizConfusion2)) <span class="sc">/</span> <span class="fu">sum</span>(matrizConfusion2)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>accuracy2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9076305</code></pre>
</div>
</div>
<p><strong><code>2.QDA.</code></strong></p>
<p>Al igual que con LDA no vamos a definir las probabilidades de perternecia a priori para cada clase. También se lleva acabo por validación cruzada.</p>
<ul>
<li><strong>Análisis discriminante cuadrático para la clasificación hecha por hclust.</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co">#QDACV&lt;-qda(dsClasified[,1:15],dsClasified$g4,CV=TRUE)</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="co">#table(dsClasified$g4,QDACV$class) </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>No deja aplicar el QDA para la clasificación hecha por hclust, dado que hay un grupo demasiado pequeño, como es el grupo 4 de hclust, compuesto por 15 individuos.</p>
<ul>
<li><strong>Análisis discriminante cuadrático para la clasificación hecha por Kmeans.</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>QDACV2<span class="ot">&lt;-</span><span class="fu">qda</span>(dsClasified[,<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>],dsClasified<span class="sc">$</span>Y,<span class="at">CV=</span><span class="cn">TRUE</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>matrizConfusion3 <span class="ot">&lt;-</span> <span class="fu">table</span>(dsClasified<span class="sc">$</span>Y,QDACV2<span class="sc">$</span>class, <span class="at">dnn=</span><span class="fu">c</span>(<span class="st">"real"</span>,<span class="st">"predicho"</span>)) </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>matrizConfusion3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    predicho
real  1  2  3  4
   1 73  4  2  2
   2  2 48  5  0
   3 17 10 22  5
   4  9  0  4 46</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>accuracy3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(matrizConfusion3)) <span class="sc">/</span> <span class="fu">sum</span>(matrizConfusion3)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>accuracy3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7590361</code></pre>
</div>
</div>
<p><strong><code>3.Recopilación Resultados</code></strong></p>
<p>Finalmente, comparamos los resultados obtenidos:</p>
<p>Para el LDA, la eficiencia es:</p>
<ul>
<li><span class="math inline">\(211/249 = 0.85\)</span> si cojo la clasificación de <strong>hclust</strong></li>
<li><span class="math inline">\(226/249 = 0.9\)</span> si cojo la clasificación de <strong>kmeans</strong></li>
</ul>
<p>Para el QDA, la eficiencia es:</p>
<ul>
<li>No me permite coger los datos del hclust por haber un grupo con pocos individuos, lo cual es un problema que deriva directamente del desbalanceo que sufren los datos.</li>
<li><span class="math inline">\(189/249 = 0.75\)</span> si cojo la clasificación de <strong>kmeans.</strong></li>
</ul>
<p>Para los datos con los que trabajamos, resulta mejor la aplicación de un análisis discriminante lineal, ya que se obtienen mejores resultados con este que con el cuadrático. Además de que el análisis cuadrático no permite trabajar con grupos pequeños, de ahí el error que se muestra al intentar aplicarlo para la clasificación hecha por el hclust, que tiene un grupo con solo 15 individuos.</p>
<p>Fijándonos solamente el el análisis discriminante lineal, aunque la diferencia no es muy significativa, la clasificación de los datos agrupados por el algortimo Kmeans resulta ser algo más eficiente que para la agrupación por hclust. Obteniédose una exactitud del 85% en la clasificación de los grupos de hclust, frente a un 90% en la clasificación de los grupos de kmeans. Esto puede que se deba a que la agrupación hecha por Kmeans presenta un menor debalanceo que a la de hclust.</p>
<ul>
<li><strong>Conocer las variables más influyentes a la hora de discriminar</strong></li>
</ul>
<p>Para la agrupación que ha resultado ser la más exacta a la hora de discriminar, merece poder conocerse cuales son las variables que más influyen a la hora de distinguir si un individuo debe pertenecer a uno u otro grupo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                LD1         LD2          LD3
Density -0.92871026  0.67704161 -0.121969468
BodyFat -0.26773037 -0.40215865 -0.869374127
Age      0.10913969 -0.21179829  0.004336141
Weight   0.28944144 -0.18135608  4.838927686
Height   0.14203049  0.50532471 -1.390141002
Neck     0.38827075  0.49489423 -0.269586525
Chest    0.54465420  0.15336569 -1.185218797
Abdomen -0.20921349  0.11265065 -0.513766036
Hip      0.28622390  0.50402043  0.173175749
Thigh    0.47800106 -0.23068258 -1.505302721
Knee     0.26994204 -0.53277046  0.232811100
Ankle    0.14518666  0.19473755 -0.469521147
Biceps  -0.06054826  0.01886978  0.305727727
Forearm  0.34814466  0.16088753 -0.165216332
Wrist    0.02161552  0.18386047 -0.726118482</code></pre>
</div>
</div>
<p>Al mostrar la matriz de ‘scaling’ tenemos 3 componentes discriminantes. Estos son combinaciones lineales de variables predictoras que utiliza el Análisis Discriminante para discriminar entre los diferentes grupos en un conjunto de datos.</p>
<p>Cada componente discriminante captura una cierta cantidad de información sobre la estructura de separación entre las clases en los datos. Y se ordenan según su capacidad para discriminar entre las clases. El primer componente discriminante captura la mayor parte de la variabilidad entre las clases 87.71%, el segundo un 10.41% y el tercero 1.88%.</p>
<p>Entonces, atendiendo a que el primer componente discriminante es el de mayor capacidad de discriminación, las variables más relevantes son la <u>densidad corporal, y el tamaño del pecho y muslo</u>.</p>
</section>
<section id="regresión-lineal-múltiple" class="level3">
<h3 class="anchored" data-anchor-id="regresión-lineal-múltiple">REGRESIÓN LINEAL MÚLTIPLE:</h3>
<p>Dado que la principal motivación con la que se recopilaron los datos de este estudio, fue para sacar conclusiones acerca de la estructura corporal de los hombres, vamos a llevar a cabo un análisis de regresión lineal múltiple. De esta forma podremos obtener un modelo que nos permita encontrar una forma de predecir el tamaño de alguna parte del cuerpo atendiendo al resto de medidas.</p>
<p>La regresión lineal la llevaremos a cabo con el dataset data, que no contempla las columnas de calsificación añadidas en apartados anteriores. Tampoco podemos aplicar los datos estandarizados ya que algunas funciones que usaremos (como boxcox()) no aceptan trabajar con una variable respuesta que presente valores negativos, como ocurre al estandarizar los datos.</p>
<section id="predicción-de-la-variable-biceps" class="level4">
<h4 class="anchored" data-anchor-id="predicción-de-la-variable-biceps"><u><strong>1.Predicción de la variable Biceps</strong></u></h4>
<p>En el estudio incial, con la gráfica qqnorm() vimos como la variable Biceps era una de las que mejor parecía seguir una variable normal, por lo que intentaremos encontrar un modelo que prediga el tamaño del biceps del hombre en función del resto de variables.</p>
<p><strong>1.1 Análisis previo de la variable respuesta</strong></p>
<p>Analizaremos brevemente la normalidad de la variable Biceps, y veremos si requiere de alguna transformación en los datos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-87-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>Vemos de nuevo al individuo 39 como un atípico para el tamaño del biceps, lo cual, nos pueda suponer un problema a la hora de que los datos pasen el test de normalidad</p>
<p><span class="math display">\[
H_0: BodyFat \text{ sigue una distribución normal}
\]</span></p>
<p><span class="math display">\[
H_1: BodyFat \text{ NO sigue una distribución normal}
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.9621, p-value = 3.642e-06</code></pre>
</div>
</div>
<p>Probamos sin el atípico 39, a ver si así pasa en test de normalidad</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.98509, p-value = 0.01055</code></pre>
</div>
</div>
<p>Debemos rechazar que Biceps sigua una distribución normal. Ni excluyendo al atípico parece seguir una normal. Muy probablemente esto se deba a que la variable requiera de una transformación en sus datos (por la familia Box-Cox). Para identificar la transformación más adecuada sobre la variable respuesta, usaremos la función boxcox() del paquete MASS. Indicar que la familia de transformaciones de Box-Cox consiste en elevar la variable respuesta a un exponente λ &gt; 0, o bien tomar logaritmos neperianos si resulta λ = 0.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-90-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p>Se observa que la transformación más adecuada es la logarítmica. Por lo que creamos otra variable nueva, que sea la transformación de Biceps, a la que le volveremos a comprobar la normalidad. Y si pasa el test, será nuestra nueva variable respuesta.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>BicepsNew <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>Biceps) <span class="co">#Transfomación</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mshapiro.test</span>(<span class="fu">t</span>(data<span class="sc">$</span>BicepsNew))   <span class="co">#Comprobación de la normalidad</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Z
W = 0.9933, p-value = 0.3249</code></pre>
</div>
</div>
<p>Aceptamos la normalidad de la variable resultante de la transformación, ’ BodyFat’ , por lo que el modelo se contruye para predecir esa variable.</p>
<p>Antes de finalizar este primer apartado de análisis de la variable respuesta, cabe recordar que ya vimos en el estudio inicial de los datos, como algunas variables presentaban una fuerte relación lineal, lo cual nos podría resultar en problemas de multicolinealidad.</p>
<p><strong>1.2 Construcción de un modelo inicial.</strong></p>
<p>Primeramente, vamos a definir 2 subconjuntos, uno de entrenamiento o train, con el que construiremos el modelo y otro de test, con el que evaluaremos que tal predice nuestro modelo. De esta forma podremos evaluar qué tal se comporta con datos nuevos, teniendo así una métrica más fiable de qué tan bueno es el modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>indices_entrenamiento <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(data), <span class="fl">0.8</span><span class="sc">*</span><span class="fu">nrow</span>(data))</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>entrenamiento <span class="ot">&lt;-</span> data[indices_entrenamiento,]</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> data[<span class="sc">-</span>indices_entrenamiento,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Construimos un modelo inicial con todas las variables, que nos pueda servir como base a partir de la cual aplicamos métodos de selección de regresores con tal de conseguir el mejor modelo posible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"rms"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Hmisc</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Hmisc'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:dplyr':

    src, summarize</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    format.pval, units</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Hmisc"</span>)</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>modelo_inicial <span class="ot">&lt;-</span> <span class="fu">lm</span>(BicepsNew <span class="sc">~</span> Density <span class="sc">+</span> BodyFat <span class="sc">+</span> Age <span class="sc">+</span> Weight <span class="sc">+</span> Height <span class="sc">+</span> Neck <span class="sc">+</span> Chest <span class="sc">+</span> Abdomen <span class="sc">+</span> Hip <span class="sc">+</span> Thigh <span class="sc">+</span> Knee <span class="sc">+</span> Ankle <span class="sc">+</span> Forearm <span class="sc">+</span> Wrist, <span class="at">data =</span> entrenamiento)</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_inicial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ Density + BodyFat + Age + Weight + Height + 
    Neck + Chest + Abdomen + Hip + Thigh + Knee + Ankle + Forearm + 
    Wrist, data = entrenamiento)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.139930 -0.028051  0.001252  0.032378  0.126131 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.5460946  1.2022592   3.781 0.000210 ***
Density     -1.4687813  1.0868279  -1.351 0.178205    
BodyFat     -0.0023692  0.0025229  -0.939 0.348905    
Age          0.0003754  0.0004127   0.910 0.364262    
Weight       0.0021606  0.0007952   2.717 0.007209 ** 
Height      -0.0036781  0.0023225  -1.584 0.114970    
Neck         0.0042729  0.0030850   1.385 0.167711    
Chest        0.0010019  0.0012941   0.774 0.439812    
Abdomen     -0.0026774  0.0013805  -1.939 0.053978 .  
Hip         -0.0031659  0.0017713  -1.787 0.075527 .  
Thigh        0.0067236  0.0017083   3.936 0.000117 ***
Knee        -0.0033997  0.0030734  -1.106 0.270089    
Ankle       -0.0001804  0.0025802  -0.070 0.944346    
Forearm      0.0108996  0.0025801   4.225 3.75e-05 ***
Wrist        0.0053418  0.0068124   0.784 0.433965    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04649 on 185 degrees of freedom
Multiple R-squared:  0.7513,    Adjusted R-squared:  0.7325 
F-statistic: 39.92 on 14 and 185 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_inicial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Density   BodyFat       Age    Weight    Height      Neck     Chest   Abdomen 
36.655854 38.653268  2.393179 49.132964  3.314997  4.919010 10.459847 20.187212 
      Hip     Thigh      Knee     Ankle   Forearm     Wrist 
14.854460  7.276212  4.771260  1.903286  2.309145  3.690887 </code></pre>
</div>
</div>
<p>Vemos como el modelo presenta una bondad de ajuste relativamente buena, por encima del 0.73.</p>
<p>Podemos también comprobar la multicolinealidad al calcular el factor de varianza inflada, para los predictores. Este factor (VIF) mide la relación lineal de cada predictor con el resto de predictores. Valores de este factor que resulten por encima de 7 son indicativo de la existencia de multicolinealidad. Entonces, sabemos que hay variables presentando multicolinealidad.</p>
<p>Destacar también que hay bastantes regresores con los p-valores correspondientes a si los coeficientes son significativos, tomando un valor alto, superior a 0.10. Esto, junto con que haya variables que presentan multicolinealidad, es indicativo de que el modelo es claramente reducible.</p>
<p><strong>1.3 Aplicación de los métodos de selección de regresores</strong>.</p>
<p>Aplicaremos los métodos de selección de regresores backward, fordward y stepwise, para intenatr optener un modelo más reducido.</p>
<p><strong>a). Modelo Backward:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>modelo_backward<span class="ot">&lt;-</span> <span class="fu">step</span>(modelo_inicial, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>b).Modelo Forward</strong></p>
<p>Para aplicar los modelos forward y stepwise, tendremos que partir de un modelo que contempla sólo la constante.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>modelo_cte <span class="ot">&lt;-</span> <span class="fu">lm</span>(BicepsNew <span class="sc">~</span> <span class="dv">1</span> , <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>modelo_forward <span class="ot">&lt;-</span> <span class="fu">step</span>(modelo_cte, <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">scope =</span> <span class="fu">formula</span>(modelo_inicial))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>c). Modelo Stepwise</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>modelo_stepwise <span class="ot">&lt;-</span> <span class="fu">step</span>(modelo_cte, <span class="at">direction =</span> <span class="st">"both"</span>,<span class="at">scope =</span> <span class="fu">formula</span>(modelo_inicial))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><strong>Comparación de los modelos</strong></p>
<p>Se observa que el modelo obtenido por backward es distinto al obtenido por los otros dos métodos.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>modelo_backward<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)       Weight       Height         Neck          Hip        Thigh 
 2.953603275  0.001835021 -0.003794422  0.004687434 -0.004361102  0.006207710 
     Forearm 
 0.011934670 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>modelo_forward<span class="sc">$</span>coefficients </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)       Weight      Forearm        Thigh         Neck        Chest 
 3.248986683  0.001351152  0.011407284  0.004662362  0.005383144  0.002058783 
     Abdomen      Density       Height 
-0.003210058 -0.511864294 -0.002833185 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>modelo_stepwise<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)       Weight      Forearm        Thigh         Neck        Chest 
 3.248986683  0.001351152  0.011407284  0.004662362  0.005383144  0.002058783 
     Abdomen      Density       Height 
-0.003210058 -0.511864294 -0.002833185 </code></pre>
</div>
</div>
<p>Debemos comparar la bondad de ajuste de los dos métodos obtenidos para así quedarnos con el mejor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_backward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ Weight + Height + Neck + Hip + Thigh + 
    Forearm, data = entrenamiento)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.151558 -0.028739 -0.000715  0.031224  0.139112 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.9536033  0.2018426  14.633  &lt; 2e-16 ***
Weight       0.0018350  0.0005136   3.573 0.000446 ***
Height      -0.0037944  0.0015689  -2.419 0.016510 *  
Neck         0.0046874  0.0028482   1.646 0.101437    
Hip         -0.0043611  0.0016674  -2.616 0.009613 ** 
Thigh        0.0062077  0.0014125   4.395 1.83e-05 ***
Forearm      0.0119347  0.0023167   5.152 6.35e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04636 on 193 degrees of freedom
Multiple R-squared:  0.742, Adjusted R-squared:  0.734 
F-statistic: 92.51 on 6 and 193 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_forward)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ Weight + Forearm + Thigh + Neck + Chest + 
    Abdomen + Density + Height, data = data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.156578 -0.031328 -0.000224  0.035597  0.275481 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.2489867  0.4310035   7.538 9.63e-13 ***
Weight       0.0013512  0.0005722   2.361 0.018999 *  
Forearm      0.0114073  0.0021696   5.258 3.21e-07 ***
Thigh        0.0046624  0.0013778   3.384 0.000834 ***
Neck         0.0053831  0.0025151   2.140 0.033329 *  
Chest        0.0020588  0.0011832   1.740 0.083134 .  
Abdomen     -0.0032101  0.0011577  -2.773 0.005993 ** 
Density     -0.5118643  0.3201473  -1.599 0.111166    
Height      -0.0028332  0.0019804  -1.431 0.153835    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05019 on 241 degrees of freedom
Multiple R-squared:  0.7114,    Adjusted R-squared:  0.7018 
F-statistic: 74.25 on 8 and 241 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Optaremos por quedarnos con el modelo backward ya que es el que mejor bondad de ajuste presenta.</p>
<p>En este modelo final, no se mejora la bondad de ajuste respecto al modelo inicial. Presenta un valor de R-cuadrado ajustado de 0.734, lo que indica que este modelo explica en un 73% la variabilidad del tamaño del biceps de un hombre. Además, no todos los regresores de este modelo final son significativos, al tener uno de ellos, Neck, un p-valor algo superior a 0.10. Esto nos indica que <u>el modelo sigue siendo reducible.</u></p>
<p><strong>1.4 Validación del modelo</strong></p>
<p>Antes de poder emplear el modelo libremente para predecir, debemos cerciorarnos de que es lo suficientemente bueno, como para considerar fiables y válidas las predicciones que se lleven a cabo con él. Se debe verificar que los residuos sigan una distribución normal y que sean independientes, que la varianza es constante en las perturbaciones aleatorias (Hipótesis de Homocedasticidad) y que no se de multicolinealidad entre variables predictoras ni existan observaciones que influyan mucho más que el resto.</p>
<p><strong><em>a).Observaciones influyentes</em></strong></p>
<p>Para comprobar que no hay observaciones influyentes, podemos calcular la distancia de Cook para cada observación. Como regla empírica, valores por encima de 1 indican que se trata de una observación influyente. En general, conviene representar los valores de la distancia de Cook con el fin de identificar si hay alguna observación con valores especialmente altos comparados con el resto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>cook <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(modelo_final)</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cook)</span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(cook,<span class="at">cex=</span><span class="fl">0.6</span>, <span class="at">labels =</span> <span class="fu">row.names</span>(entrenamiento))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-102-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p><strong><em>b).Multicolinealidad</em></strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Weight    Height      Neck       Hip     Thigh   Forearm 
20.610707  1.521175  4.215999 13.235564  5.001849  1.872244 </code></pre>
</div>
</div>
<p>Vemos como Weight presenta gran multicolinealidad, debemos quitarla y ver que ocurre.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>modelo_final <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> BicepsNew <span class="sc">~</span> Height <span class="sc">+</span> Neck <span class="sc">+</span> Hip <span class="sc">+</span> Thigh <span class="sc">+</span> Forearm, <span class="at">data =</span> entrenamiento)</span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ Height + Neck + Hip + Thigh + Forearm, 
    data = entrenamiento)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.166857 -0.030469  0.001669  0.031106  0.156923 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.3184660  0.0984736  23.544  &lt; 2e-16 ***
Height      -0.0009548  0.0013931  -0.685    0.494    
Neck         0.0108324  0.0023381   4.633 6.60e-06 ***
Hip          0.0002210  0.0010975   0.201    0.841    
Thigh        0.0068554  0.0014426   4.752 3.91e-06 ***
Forearm      0.0131142  0.0023616   5.553 9.15e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04774 on 194 degrees of freedom
Multiple R-squared:  0.7249,    Adjusted R-squared:  0.7178 
F-statistic: 102.3 on 5 and 194 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Height     Neck      Hip    Thigh  Forearm 
1.130818 2.678763 5.406259 4.919472 1.834232 </code></pre>
</div>
</div>
<p>Al quitar Weight ya no hay multicolinealidad en el modelo. Además aprovechamos para reducir el número de variables predictoras al tener Height y Hip un p-valor bastante por encima de 0.1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>modelo_final <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> BicepsNew <span class="sc">~</span> Neck <span class="sc">+</span> Thigh <span class="sc">+</span> Forearm, <span class="at">data =</span> entrenamiento)</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ Neck + Thigh + Forearm, data = entrenamiento)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.164178 -0.029431  0.001707  0.031102  0.152730 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 2.267287   0.058207  38.952  &lt; 2e-16 ***
Neck        0.010906   0.002171   5.025 1.13e-06 ***
Thigh       0.007024   0.000944   7.441 3.07e-12 ***
Forearm     0.012873   0.002326   5.534 9.94e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04756 on 196 degrees of freedom
Multiple R-squared:  0.7242,    Adjusted R-squared:   0.72 
F-statistic: 171.6 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El valor de R-cuadrado se acaba estableciendo superior al 72%.</p>
<p><strong><em>c).Hipótesis de Homocedasticidad</em></strong></p>
<p>Vemos como tiene un comportamiento aleatorio con dispersión aproximadamente constante</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-106-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p><strong><em>d)Hipótesis de Independencia</em></strong></p>
<p>Analizamos la independencia con el test de Durbin-Watson y representando la serie temporal de residuos.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lmtest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:rms':

    lrtest</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Durbin-Watson test

data:  modelo_final
DW = 1.8119, p-value = 0.174
alternative hypothesis: true autocorrelation is not 0</code></pre>
</div>
</div>
<p>Al tener un p-valor superior a 0.10 en el test de Durbin-Watson, podemos suponer independencia de las observaciones.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="ÁlvarezCascales_files/figure-html/unnamed-chunk-108-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<p><strong><em>e).Test de Normalidad de los residuos</em></strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  modelo_final$residuals
W = 0.99379, p-value = 0.5698</code></pre>
</div>
</div>
<p>El modelo pasa el test de normalidad de los residuos.</p>
<p>Se nos queda finalmente el siguiente modelo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Neck       Thigh     Forearm 
 2.26728735  0.01090604  0.00702424  0.01287354 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ Neck + Thigh + Forearm, data = entrenamiento)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.164178 -0.029431  0.001707  0.031102  0.152730 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 2.267287   0.058207  38.952  &lt; 2e-16 ***
Neck        0.010906   0.002171   5.025 1.13e-06 ***
Thigh       0.007024   0.000944   7.441 3.07e-12 ***
Forearm     0.012873   0.002326   5.534 9.94e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04756 on 196 degrees of freedom
Multiple R-squared:  0.7242,    Adjusted R-squared:   0.72 
F-statistic: 171.6 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>1.5 Intento de mejora del modelo</strong></p>
<p>Una vez que hemos comprobado que tenemos un modelo válido que pasa todas las comprobaciones necesarias podemos intentar probar a ajustarlo más, elevando a alguna potencia las variables predictoras.</p>
<p>No debemos pasarnos, por lo que entraríamos en problemas de sobreajuste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>modelo_final_mejorado <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> BicepsNew <span class="sc">~</span> <span class="fu">I</span>(Neck<span class="sc">^</span><span class="dv">4</span>) <span class="sc">+</span> Thigh <span class="sc">+</span> <span class="fu">pol</span>(Forearm,<span class="dv">3</span>), <span class="at">data =</span> entrenamiento)</span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_final_mejorado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BicepsNew ~ I(Neck^4) + Thigh + pol(Forearm, 3), 
    data = entrenamiento)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.125680 -0.030966  0.001398  0.035231  0.161395 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               1.331e+01  3.232e+00   4.120 5.62e-05 ***
I(Neck^4)                 3.845e-08  8.131e-09   4.729 4.33e-06 ***
Thigh                     6.080e-03  9.642e-04   6.306 1.89e-09 ***
pol(Forearm, 3)Forearm   -1.153e+00  3.405e-01  -3.385 0.000862 ***
pol(Forearm, 3)Forearm^2  4.206e-02  1.195e-02   3.520 0.000538 ***
pol(Forearm, 3)Forearm^3 -5.013e-04  1.392e-04  -3.602 0.000401 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0462 on 194 degrees of freedom
Multiple R-squared:  0.7424,    Adjusted R-squared:  0.7357 
F-statistic: 111.8 on 5 and 194 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Al aplicar un polinomio de grado 3 a la variable Forearm, y elevar a potencia 4 a la variable Neck, conseguimos mejorar un poco el ajuste hasta superar el 74%.</p>
<p>Siendo finalmente los coeficientes del modelo mejorado:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             (Intercept)                I(Neck^4)                    Thigh 
            1.331439e+01             3.845410e-08             6.079952e-03 
  pol(Forearm, 3)Forearm pol(Forearm, 3)Forearm^2 pol(Forearm, 3)Forearm^3 
           -1.152636e+00             4.206177e-02            -5.012717e-04 </code></pre>
</div>
</div>
<p><strong>1.6 Predicciones</strong></p>
<p>Ahora debemos probar a emplear el modelo para ver qué tal trabaja.</p>
<p>Podemos emplearlo para dar un intervalo de los valores posibles que pueden tomar los coeficientes. Cualquier modelo teórico con coeficientes incluidos en el intervalo siguiente serían también válidos teniendo en cuenta nuestros datos muestrales</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                 2.5 %        97.5 %
(Intercept)               6.940164e+00  1.968861e+01
I(Neck^4)                 2.241766e-08  5.449054e-08
Thigh                     4.178329e-03  7.981575e-03
pol(Forearm, 3)Forearm   -1.824231e+00 -4.810406e-01
pol(Forearm, 3)Forearm^2  1.849184e-02  6.563169e-02
pol(Forearm, 3)Forearm^3 -7.757549e-04 -2.267884e-04</code></pre>
</div>
</div>
<p>Para la predicción empleando nuevos valores, utilizaremos la función predict que permitirá obtener tanto valores de predicción como intervalos de confianza para el valor medio de la respuesta y para el valor de la respuesta utilizando la opción en el argumento interval = “confidence” e interval = “prediction”, respectivamente.</p>
<p>Una de las prácticas más comunes en el ámbito de la ciencia de datos es probar con los datos de test, los modelos construidos con los datos de entrnamiento. Y tasar la eficiencia de estos calculando algunas de sus métricas.</p>
<p>En nuestro caso calcularemos las métricas <strong>MSE</strong> (Error cuadrático medio) y <strong>MAE</strong> (Error absoluto medio)</p>
<p><span class="math display">\[MSE = E((h(X) − Y )^2).\]</span></p>
<p><span class="math display">\[
MAE = E(|h(X) - Y|)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_final_mejorado, <span class="at">newdata =</span> test, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(predicciones)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Debemos de tener en cuenta que las predicciones son sobre la variable BicepsNew, y no sobre la variable original Biceps. Es decir las predicciones obtenidas están bajo la transformación de la familia Box-Cox, por lo que antes de calcular el MSE o MAE, se debe de deshacer dicha transformación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Deshacer la transformación</span></span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">exp</span>(predicciones<span class="sc">$</span>fit)</span>
<span id="cb156-3"><a href="#cb156-3" aria-hidden="true" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> <span class="fu">mean</span>((test<span class="sc">$</span>Biceps <span class="sc">-</span> p)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb156-4"><a href="#cb156-4" aria-hidden="true" tabindex="-1"></a>RMSE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(MSE)</span>
<span id="cb156-5"><a href="#cb156-5" aria-hidden="true" tabindex="-1"></a>MAE <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test<span class="sc">$</span>Biceps <span class="sc">-</span> p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a>MSE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.930071</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>RMSE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.982441</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a>MAE</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.371291</code></pre>
</div>
</div>
<p>El MSE al estar elevado al cuadrado, es bastante sensible a errores de predicción, y más aún si trabaja con algún atípico. Un MSE de 3.93 unidades con respecto a las observaciones reales pueda parecer un error alto para el contexto en el que nos movemos, ya que la circunferncia del biceps está más o menos en torno a un rango de 25 a 35 cm.</p>
<p>Pero si le hacemos la raiz cuadrada, es decir el RMSE, vemos como esta variación entre las predicciones y observaciones reales se reduce a la mitad.</p>
<p>Por otro lado, el MAE, indica que, en promedio, las predicciones del modelo se desvían aproximadamente en 1.37 unidades de las observaciones reales en valor absoluto.</p>
<p>Teniendo esto en cuenta, podemos decir que los errores no son excesivamente grandes a pesar de que la bondad de ajuste del modelo no supere el 75%.</p>
<p>Podemos considerarlo como un modelo relativamente bueno, que tiene la capacidad adecuada para dar una predicción cercana a la realidad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Biceps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  25.30   30.30   32.10   32.32   34.38   45.00 </code></pre>
</div>
</div>
<p><code>-Para el individuo 182</code></p>
<p>También podemos testear el modelo más a fondo y ver que nos retorna con los individuos que descartamos al inicio de este estudio. Por ejemplo emplearemos al individuo 182 con tal de predecir su tamaño del biceps en función del tamaño de su antebrazos, muslo, y cuello .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a>d182 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Forearm =</span> d<span class="sc">$</span>Forearm[<span class="dv">182</span>], <span class="at">Thigh =</span> d<span class="sc">$</span>Thigh[<span class="dv">182</span>], <span class="at">Neck =</span> d<span class="sc">$</span>Neck[<span class="dv">182</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Intervalo para el valor de la respuesta</span></span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo_final_mejorado, <span class="at">newdata =</span> d182, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 3.288416 3.164182 3.412649</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">3.288416</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26.80038</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb170"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb170-1"><a href="#cb170-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>Biceps[<span class="dv">182</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27.7</code></pre>
</div>
</div>
<p>Vemos como la predicción es relativamente buena para no tener el modelo una bondad de ajuste especialmente alta, se equivoca en menos de 1 cm.</p>
</section>
<section id="aplicación-del-algoritmo-del-gradiente-descendente." class="level4">
<h4 class="anchored" data-anchor-id="aplicación-del-algoritmo-del-gradiente-descendente."><strong>2.Aplicación del Algoritmo del gradiente descendente.</strong></h4>
<p>Resulta interesante poder comparar los coeficientes del modelo estimados por medio del algoritmo del gradiente, con los coeficientes obtenidos por medio de la función lm(), que emplea el método de mínimos cuadrados.</p>
<p>El código empleado es una modificación del ofrecido en la práctica 2 de la asignatura Análisis Estadístico Multivariante.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb172"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb172-1"><a href="#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Vector de unos</span></span>
<span id="cb172-2"><a href="#cb172-2" aria-hidden="true" tabindex="-1"></a>x0_RLM <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">length</span>(entrenamiento<span class="sc">$</span>BicepsNew)))</span>
<span id="cb172-3"><a href="#cb172-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Debemos tener en cuenta que la variable respuesta del modelo es BicepsNew</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb173"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb173-1"><a href="#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Regresores</span></span>
<span id="cb173-2"><a href="#cb173-2" aria-hidden="true" tabindex="-1"></a>forearm <span class="ot">&lt;-</span> entrenamiento<span class="sc">$</span>Forearm</span>
<span id="cb173-3"><a href="#cb173-3" aria-hidden="true" tabindex="-1"></a>thigh <span class="ot">&lt;-</span> entrenamiento<span class="sc">$</span>Thigh</span>
<span id="cb173-4"><a href="#cb173-4" aria-hidden="true" tabindex="-1"></a>neck <span class="ot">&lt;-</span>entrenamiento<span class="sc">$</span>Neck</span>
<span id="cb173-5"><a href="#cb173-5" aria-hidden="true" tabindex="-1"></a>chest <span class="ot">&lt;-</span> entrenamiento<span class="sc">$</span>Chest</span>
<span id="cb173-6"><a href="#cb173-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Variable Respuesta</span></span>
<span id="cb173-7"><a href="#cb173-7" aria-hidden="true" tabindex="-1"></a>biceps <span class="ot">&lt;-</span> entrenamiento<span class="sc">$</span>BicepsNew</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb174"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb174-1"><a href="#cb174-1" aria-hidden="true" tabindex="-1"></a>n_RLM <span class="ot">&lt;-</span><span class="fu">length</span>(x0_RLM)</span>
<span id="cb174-2"><a href="#cb174-2" aria-hidden="true" tabindex="-1"></a>variables<span class="ot">&lt;-</span><span class="fu">data.frame</span>(x0_RLM,forearm,thigh,neck,chest,biceps)</span>
<span id="cb174-3"><a href="#cb174-3" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="co">#Número de regresores</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb175"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb175-1"><a href="#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Metemos los datos muestrales en una matriz M (matriz de diseño)</span></span>
<span id="cb175-2"><a href="#cb175-2" aria-hidden="true" tabindex="-1"></a>M<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="dv">1</span>,n_RLM,k<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb175-3"><a href="#cb175-3" aria-hidden="true" tabindex="-1"></a>M[,<span class="dv">2</span>]<span class="ot">&lt;-</span>forearm</span>
<span id="cb175-4"><a href="#cb175-4" aria-hidden="true" tabindex="-1"></a>M[,<span class="dv">3</span>]<span class="ot">&lt;-</span>thigh</span>
<span id="cb175-5"><a href="#cb175-5" aria-hidden="true" tabindex="-1"></a>M[,<span class="dv">4</span>]<span class="ot">&lt;-</span>neck</span>
<span id="cb175-6"><a href="#cb175-6" aria-hidden="true" tabindex="-1"></a>M[,<span class="dv">5</span>]<span class="ot">&lt;-</span>chest</span>
<span id="cb175-7"><a href="#cb175-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Definimos función costo usando la matriz de diseño M</span></span>
<span id="cb175-8"><a href="#cb175-8" aria-hidden="true" tabindex="-1"></a>h_RLM<span class="ot">&lt;-</span><span class="cf">function</span>(theta,x) {<span class="fu">sum</span>(theta<span class="sc">*</span>x)}</span>
<span id="cb175-9"><a href="#cb175-9" aria-hidden="true" tabindex="-1"></a>J_RLM<span class="ot">&lt;-</span><span class="cf">function</span>(theta,M) {<span class="fl">0.5</span><span class="sc">*</span><span class="fu">sum</span>((M <span class="sc">%*%</span>theta<span class="sc">-</span> biceps)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>n_RLM}</span>
<span id="cb175-10"><a href="#cb175-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Fijamos iteraciones, learning rate y valores iniciales</span></span>
<span id="cb175-11"><a href="#cb175-11" aria-hidden="true" tabindex="-1"></a>m_RLM <span class="ot">&lt;-</span><span class="dv">50</span> <span class="co"># Número de interaciones</span></span>
<span id="cb175-12"><a href="#cb175-12" aria-hidden="true" tabindex="-1"></a>alfa_RLM <span class="ot">&lt;-</span><span class="fl">0.1</span> <span class="co"># learning rate</span></span>
<span id="cb175-13"><a href="#cb175-13" aria-hidden="true" tabindex="-1"></a>theta_RLM <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>) <span class="co">#valores iniciales de los theta</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb176"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb176-1"><a href="#cb176-1" aria-hidden="true" tabindex="-1"></a>J2_RLM<span class="ot">&lt;-</span> <span class="fu">array</span>() <span class="co">#Vector con actualizaciones de la función costo en cada iteración</span></span>
<span id="cb176-2"><a href="#cb176-2" aria-hidden="true" tabindex="-1"></a>hv_RLM<span class="ot">&lt;-</span> <span class="fu">array</span>() <span class="co">#Vector con actualizaciones de los valores ajustados en cada iteración</span></span>
<span id="cb176-3"><a href="#cb176-3" aria-hidden="true" tabindex="-1"></a>Z2_RLM<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="cn">NA</span>,m_RLM<span class="sc">+</span><span class="dv">1</span>,k<span class="sc">+</span><span class="dv">1</span>) <span class="co">#Matriz con actualizaciones de los theta en cada iteración</span></span>
<span id="cb176-4"><a href="#cb176-4" aria-hidden="true" tabindex="-1"></a>J2_RLM[<span class="dv">1</span>]<span class="ot">&lt;-</span><span class="fu">J_RLM</span>(theta_RLM,M)</span>
<span id="cb176-5"><a href="#cb176-5" aria-hidden="true" tabindex="-1"></a>Z2_RLM[<span class="dv">1</span>,]<span class="ot">&lt;-</span>theta_RLM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb177"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb177-1"><a href="#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>m_RLM) {</span>
<span id="cb177-2"><a href="#cb177-2" aria-hidden="true" tabindex="-1"></a>hv_RLM<span class="ot">&lt;-</span> M<span class="sc">%*%</span>theta_RLM</span>
<span id="cb177-3"><a href="#cb177-3" aria-hidden="true" tabindex="-1"></a>theta_RLM <span class="ot">&lt;-</span> theta_RLM <span class="sc">-</span> (alfa_RLM<span class="sc">/</span>n_RLM) <span class="sc">*</span> <span class="fu">t</span>(M)<span class="sc">%*%</span>(hv_RLM<span class="sc">-</span>biceps)</span>
<span id="cb177-4"><a href="#cb177-4" aria-hidden="true" tabindex="-1"></a>J2_RLM[i<span class="sc">+</span><span class="dv">1</span>]<span class="ot">&lt;-</span><span class="fu">J_RLM</span>(theta_RLM,M)</span>
<span id="cb177-5"><a href="#cb177-5" aria-hidden="true" tabindex="-1"></a>Z2_RLM[i<span class="sc">+</span><span class="dv">1</span>,] <span class="ot">&lt;-</span> theta_RLM</span>
<span id="cb177-6"><a href="#cb177-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb178"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb178-1"><a href="#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Guardamos los valores de los theta y del costo en un dataframe</span></span>
<span id="cb178-2"><a href="#cb178-2" aria-hidden="true" tabindex="-1"></a>resultados_RLM <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Z2_RLM, J2_RLM)</span>
<span id="cb178-3"><a href="#cb178-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(resultados_RLM) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"theta0"</span>, <span class="st">"theta1"</span>, <span class="st">"theta2"</span>,<span class="st">"theta3"</span>,<span class="st">"theta4"</span>, <span class="st">"costo"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb179"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb179-1"><a href="#cb179-1" aria-hidden="true" tabindex="-1"></a>A<span class="ot">&lt;-</span><span class="fu">t</span>(M) <span class="sc">%*%</span> M</span>
<span id="cb179-2"><a href="#cb179-2" aria-hidden="true" tabindex="-1"></a>B<span class="ot">&lt;-</span><span class="fu">solve</span>(A)</span>
<span id="cb179-3"><a href="#cb179-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A %*%B</span></span>
<span id="cb179-4"><a href="#cb179-4" aria-hidden="true" tabindex="-1"></a>thetas_exactos <span class="ot">&lt;-</span>B <span class="sc">%*%</span> <span class="fu">t</span>(M) <span class="sc">%*%</span> biceps</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Coeficientes obtenidos con el gradiente descendente:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
[1,] 2.275520728
[2,] 0.012346893
[3,] 0.006303383
[4,] 0.007939189
[5,] 0.001608672</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Coeficientes obtenidos con el método de mínimos cuadrados: "</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Neck       Thigh     Forearm 
 2.26728735  0.01090604  0.00702424  0.01287354 </code></pre>
</div>
</div>
<p>Se alcanzan por ambos métodos los mismos coeficientes del modelo. Aunque resulta más cómodo hacerlo solo por medio de la función lm() que solo requiere una única instrucción.</p>
</section>
</section>
<section id="consideraciones-finales." class="level3">
<h3 class="anchored" data-anchor-id="consideraciones-finales.">Consideraciones Finales.</h3>
<p>Este trabajo me ha supuesto un primer contacto real no supervisado con el mundo del análisis de datos. Para llevarlo a cabo me he guiado por los archivos de la asignatura Análisis Estadístico Multivariante proporcionados por los profesores Concepción Domínguez y Jorge Navarro.</p>
<p>La redacción de este informe me ha permitido adquirir experiencia en la interpretación de los resultados, y también en la toma de decisiones informadas conforme a esos resultados que se van obteniendo durante el propio análisis de los datos.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>